/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Wed May 25 14:09:26 2022"
#define BUILD_TIME (1653476966UL)

#define VERSION_NUMBER 0x04010018UL
#define VERSION_FEATURES 0x000e0000UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x353b01fdUL
#define VERSION_SANITY2 0x405093a2dc8UL
#define VERSION_SANITY3 0x00040000UL

#define VERSION_STRING "4.1.0"
#define VERSION_ID \
 "Unix GnollHack Version 4.1.0 Beta 4 - last build Wed May 25 14:09:26 2022."
#define COPYRIGHT_BANNER_C \
 "         Version 4.1.0 Unix Beta 4, built May 25 14:09:26 2022."

