/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Sun May 23 19:06:52 2021"
#define BUILD_TIME (1621786012UL)

#define VERSION_NUMBER 0x04010003UL
#define VERSION_FEATURES 0x000e0040UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x343ac1f8UL
#define VERSION_SANITY2 0x4053129cdc8UL
#define VERSION_SANITY3 0x0003a000UL

#define VERSION_STRING "4.1.0"
#define VERSION_ID \
 "Unix GnollHack Version 4.1.0 Pre-Alpha 3 - last build Sun May 23 19:06:52 2021."
#define COPYRIGHT_BANNER_C \
 "         Version 4.1.0 Unix Pre-Alpha 3, built May 23 19:06:52 2021."

