/*
 * action.h
 * Copyright (c) Janne Gustafsson, 2020
 *
 */

#ifndef ACTION_H
#define ACTION_H

/* Action tiles */
enum action_tile_types
{
    ACTION_TILE_NO_ACTION = 0,
    ACTION_TILE_ATTACK,
    ACTION_TILE_THROW,
    ACTION_TILE_FIRE,
	ACTION_TILE_CAST_NODIR,
	ACTION_TILE_CAST_DIR,
	ACTION_TILE_SPECIAL_ATTACK,
    ACTION_TILE_KICK,
    ACTION_TILE_PASSIVE_DEFENSE,
    ACTION_TILE_DEFEND,
    ACTION_TILE_RECEIVE_DAMAGE,
    ACTION_TILE_ITEM_USE,
    ACTION_TILE_DOOR_USE,
    ACTION_TILE_DEATH,
    MAX_ACTION_TILES
};


#define ACTION_ITEM_USE_NONE        0x00000001UL
#define ACTION_ITEM_USE_CAMERA      0x00000002UL
#define ACTION_ITEM_USE_PICK_AXE    0x00000004UL
#define ACTION_ITEM_USE_JAR         0x00000008UL
#define ACTION_ITEM_USE_POTION      0x00000010UL
#define ACTION_ITEM_USE_SCROLL      0x00000020UL


#endif /* ACTION_H */