/*
 * animation.h
 * Copyright (c) Janne Gustafsson, 2020
 */
#include "general.h"
#include "action.h"
#include "layer.h"

#ifndef ANIMATION_H
#define ANIMATION_H



/* Autodraw */
enum autodraw_types
{
    AUTODRAW_NONE = 0,
    AUTODRAW_DUNGEON_NORMAL_REPLACE_WALL_ENDS_ALL,
    AUTODRAW_DUNGEON_NORMAL_REPLACE_WALL_ENDS_LEFT_RIGHT,
    AUTODRAW_DUNGEON_NORMAL_REPLACE_WALL_ENDS_UP_DOWN,
    AUTODRAW_DUNGEON_NORMAL_REPLACE_WALL_ENDS_UP_DOWN_LEFT,
    AUTODRAW_DUNGEON_NORMAL_REPLACE_WALL_ENDS_UP_DOWN_RIGHT,
    AUTODRAW_DUNGEON_NORMAL_REPLACE_WALL_ENDS_UP_LEFT_RIGHT,
    AUTODRAW_DUNGEON_NORMAL_REPLACE_WALL_ENDS_DOWN_LEFT_RIGHT,
    AUTODRAW_DUNGEON_NORMAL_REPLACE_WALL_ENDS_DOWN_RIGHT,
    AUTODRAW_DUNGEON_NORMAL_REPLACE_WALL_ENDS_DOWN_LEFT,
    AUTODRAW_DUNGEON_NORMAL_REPLACE_WALL_ENDS_UP_RIGHT,
    AUTODRAW_DUNGEON_NORMAL_REPLACE_WALL_ENDS_UP_LEFT,
    AUTODRAW_GNOMISH_MINES_REPLACE_WALL_ENDS_ALL,
    AUTODRAW_GNOMISH_MINES_REPLACE_WALL_ENDS_LEFT_RIGHT,
    AUTODRAW_GNOMISH_MINES_REPLACE_WALL_ENDS_UP_DOWN,
    AUTODRAW_GNOMISH_MINES_REPLACE_WALL_ENDS_UP_DOWN_LEFT,
    AUTODRAW_GNOMISH_MINES_REPLACE_WALL_ENDS_UP_DOWN_RIGHT,
    AUTODRAW_GNOMISH_MINES_REPLACE_WALL_ENDS_UP_LEFT_RIGHT,
    AUTODRAW_GNOMISH_MINES_REPLACE_WALL_ENDS_DOWN_LEFT_RIGHT,
    AUTODRAW_GNOMISH_MINES_REPLACE_WALL_ENDS_DOWN_RIGHT,
    AUTODRAW_GNOMISH_MINES_REPLACE_WALL_ENDS_DOWN_LEFT,
    AUTODRAW_GNOMISH_MINES_REPLACE_WALL_ENDS_UP_RIGHT,
    AUTODRAW_GNOMISH_MINES_REPLACE_WALL_ENDS_UP_LEFT,
    AUTODRAW_GEHENNOM_REPLACE_WALL_ENDS_ALL,
    AUTODRAW_GEHENNOM_REPLACE_WALL_ENDS_LEFT_RIGHT,
    AUTODRAW_GEHENNOM_REPLACE_WALL_ENDS_UP_DOWN,
    AUTODRAW_GEHENNOM_REPLACE_WALL_ENDS_UP_DOWN_LEFT,
    AUTODRAW_GEHENNOM_REPLACE_WALL_ENDS_UP_DOWN_RIGHT,
    AUTODRAW_GEHENNOM_REPLACE_WALL_ENDS_UP_LEFT_RIGHT,
    AUTODRAW_GEHENNOM_REPLACE_WALL_ENDS_DOWN_LEFT_RIGHT,
    AUTODRAW_GEHENNOM_REPLACE_WALL_ENDS_DOWN_RIGHT,
    AUTODRAW_GEHENNOM_REPLACE_WALL_ENDS_DOWN_LEFT,
    AUTODRAW_GEHENNOM_REPLACE_WALL_ENDS_UP_RIGHT,
    AUTODRAW_GEHENNOM_REPLACE_WALL_ENDS_UP_LEFT, AUTODRAW_DUNGEON_UNDEAD_REPLACE_WALL_ENDS_ALL,
    AUTODRAW_DUNGEON_UNDEAD_REPLACE_WALL_ENDS_LEFT_RIGHT,
    AUTODRAW_DUNGEON_UNDEAD_REPLACE_WALL_ENDS_UP_DOWN,
    AUTODRAW_DUNGEON_UNDEAD_REPLACE_WALL_ENDS_UP_DOWN_LEFT,
    AUTODRAW_DUNGEON_UNDEAD_REPLACE_WALL_ENDS_UP_DOWN_RIGHT,
    AUTODRAW_DUNGEON_UNDEAD_REPLACE_WALL_ENDS_UP_LEFT_RIGHT,
    AUTODRAW_DUNGEON_UNDEAD_REPLACE_WALL_ENDS_DOWN_LEFT_RIGHT,
    AUTODRAW_DUNGEON_UNDEAD_REPLACE_WALL_ENDS_DOWN_RIGHT,
    AUTODRAW_DUNGEON_UNDEAD_REPLACE_WALL_ENDS_DOWN_LEFT,
    AUTODRAW_DUNGEON_UNDEAD_REPLACE_WALL_ENDS_UP_RIGHT,
    AUTODRAW_DUNGEON_UNDEAD_REPLACE_WALL_ENDS_UP_LEFT,
    AUTODRAW_GEHENNOM_CAVERNOUS_REPLACE_WALL_ENDS_ALL,
    AUTODRAW_GEHENNOM_CAVERNOUS_REPLACE_WALL_ENDS_LEFT_RIGHT,
    AUTODRAW_GEHENNOM_CAVERNOUS_REPLACE_WALL_ENDS_UP_DOWN,
    AUTODRAW_GEHENNOM_CAVERNOUS_REPLACE_WALL_ENDS_UP_DOWN_LEFT,
    AUTODRAW_GEHENNOM_CAVERNOUS_REPLACE_WALL_ENDS_UP_DOWN_RIGHT,
    AUTODRAW_GEHENNOM_CAVERNOUS_REPLACE_WALL_ENDS_UP_LEFT_RIGHT,
    AUTODRAW_GEHENNOM_CAVERNOUS_REPLACE_WALL_ENDS_DOWN_LEFT_RIGHT,
    AUTODRAW_GEHENNOM_CAVERNOUS_REPLACE_WALL_ENDS_DOWN_RIGHT,
    AUTODRAW_GEHENNOM_CAVERNOUS_REPLACE_WALL_ENDS_DOWN_LEFT,
    AUTODRAW_GEHENNOM_CAVERNOUS_REPLACE_WALL_ENDS_UP_RIGHT,
    AUTODRAW_GEHENNOM_CAVERNOUS_REPLACE_WALL_ENDS_UP_LEFT, 
    AUTODRAW_BOOKSHELF,
    AUTODRAW_WEAPON_RACK,
    AUTODRAW_CANDELABRUM,
    AUTODRAW_CANDELABRUM_ANIMATION_TILE_1,
    AUTODRAW_LARGE_FIVE_BRANCHED_CANDELABRUM,
    AUTODRAW_LARGE_FIVE_BRANCHED_CANDELABRUM_ANIMATION_TILE_1,
    AUTODRAW_LARGE_FIVE_BRANCHED_CANDELABRUM_ANIMATION_TILE_2,
    AUTODRAW_LARGE_FIVE_BRANCHED_CANDELABRUM_ANIMATION_TILE_3,
    AUTODRAW_LARGE_FIVE_BRANCHED_CANDELABRUM_ANIMATION_TILE_4,
    AUTODRAW_LARGE_FIVE_BRANCHED_CANDELABRUM_ANIMATION_TILE_5,
    AUTODRAW_JAR_YELLOW,
    AUTODRAW_JAR_PURPLE,
    AUTODRAW_JAR_WHITE,
    AUTODRAW_JAR_VIOLET,
    AUTODRAW_JAR_CRIMSON,
    AUTODRAW_FIGURINE,
    AUTODRAW_CHAIN,
    AUTODRAW_BALL,
    AUTODRAW_CHAIN_UP,
    AUTODRAW_CHAIN_RIGHT,
    AUTODRAW_CHAIN_DOWN,
    AUTODRAW_CHAIN_LEFT,
    AUTODRAW_LONG_WORM_HEAD,
    AUTODRAW_LONG_WORM_TAIL,
    AUTODRAW_ELDER_LONG_WORM_HEAD,
    AUTODRAW_ELDER_LONG_WORM_TAIL,
    AUTODRAW_COFFIN,
    MAX_AUTODRAWS
};

enum autodraw_drawing_types
{
    AUTODRAW_DRAW_GENERAL = 0,
    AUTODRAW_DRAW_REPLACE_WALL_ENDS,
    AUTODRAW_DRAW_BOOKSHELF_CONTENTS,
    AUTODRAW_DRAW_WEAPON_RACK_CONTENTS,
    AUTODRAW_DRAW_COFFIN_CONTENTS,
    AUTODRAW_DRAW_CANDELABRUM_CANDLES,
    AUTODRAW_DRAW_LARGE_FIVE_BRANCHED_CANDELABRUM_CANDLES,
    AUTODRAW_DRAW_JAR_CONTENTS,
    AUTODRAW_DRAW_FIGURINE,
    AUTODRAW_DRAW_CHAIN,
    AUTODRAW_DRAW_BALL,
    AUTODRAW_DRAW_LONG_WORM,
};


struct autodraw_definition {
    const char* autodraw_name;
    enum autodraw_drawing_types draw_type;
    unsigned char flags;
    int source_glyph;
    int source_glyph2;
    int source_glyph3;
    int source_glyph4;
    unsigned long parameter1;
    /* and other useful stuff if need be */
};

#define AUTODRAW_DIR_LEFT 0x01
#define AUTODRAW_DIR_RIGHT 0x02
#define AUTODRAW_DIR_UP 0x04
#define AUTODRAW_DIR_DOWN 0x08

extern NEARDATA struct autodraw_definition autodraws[];



/* Animation tiles */
#define MAX_FRAMES_PER_ANIMATION 32
#define MAX_TILES_PER_ANIMATION MAX_FRAMES_PER_ANIMATION

enum animation_play_types
{
    ANIMATION_PLAY_TYPE_ALWAYS = 0,
    ANIMATION_PLAY_TYPE_PLAYED_SEPARATELY
};

enum main_tile_use_types
{
    ANIMATION_MAIN_TILE_USE_FIRST = 0,
    ANIMATION_MAIN_TILE_USE_LAST,
    ANIMATION_MAIN_TILE_IGNORE
};

enum animation_main_types
{
    ANIMATION_TYPE_NORMAL = 0,
    ANIMATION_TYPE_MISSILE,
    ANIMATION_TYPE_ZAP,
    MAX_ANIMATION_TYPES
};

struct animation_definition {
    const char* animation_name;
    enum animation_main_types animation_type;
    char number_of_tiles;
    char number_of_frames;
    char number_of_tile_animations;
    char intervals_between_frames;
    enum animation_play_types play_type;
    enum main_tile_use_types main_tile_use_style; /* 0 = play as first tile and frame, 1 = play as last tile and frame, 2 = ignore */
    enum autodraw_types  main_tile_autodraw;
    char frame2tile[MAX_FRAMES_PER_ANIMATION];
    char sound_play_frame;
    char action_execution_frame;
    short tile_enlargement; /* Animations always use the same single enlargement */
    enum autodraw_types frame_autodraw[MAX_FRAMES_PER_ANIMATION];
};

enum animation_types
{
    NO_ANIMATION = 0,
    HANDCRAFTED_CANDLE_LIT_ANIMATION,
    BRASS_LANTERN_LIT_ANIMATION,
    LAWFUL_ALTAR_ANIMATION,
    NEUTRAL_ALTAR_ANIMATION,
    CHAOTIC_ALTAR_ANIMATION,
    ALTAR_OF_MOLOCH_ANIMATION,
    HIGH_ALTAR_ANIMATION,
    LAND_MINE_ACTIVATED_ANIMATION,
    MAGIC_TRAP_STAND_ANIMATION,
    ANTIMAGIC_TRAP_STAND_ANIMATION,
    TELEPORT_TRAP_STAND_ANIMATION,
    LEVEL_TELEPORT_TRAP_STAND_ANIMATION,
    POLYMORPH_TRAP_STAND_ANIMATION,
    STATUE_TRAP_STAND_ANIMATION,
    FIRE_TRAP_STAND_ANIMATION,
    MAGIC_PORTAL_STAND_ANIMATION,
    LOOK_CURSOR_ANIMATION,
    KOBOLD_ANIMATION,
    LARGE_KOBOLD_ANIMATION,
    KOBOLD_LORD_ANIMATION,
    KOBOLD_SHAMAN_ANIMATION,
    FREEZING_SPHERE_STAND_ANIMATION,
    FLAMING_SPHERE_STAND_ANIMATION,
    SHOCKING_SPHERE_STAND_ANIMATION,
    DRACOLICH_ATTACK_ANIMATION,
    MAGIC_FOUNTAIN_ANIMATION,
    FOUNTAIN_OF_HEALING_ANIMATION,
    FOUNTAIN_OF_MANA_ANIMATION,
    FOUNTAIN_OF_POWER_ANIMATION,
    FOUNTAIN_OF_POISON_ANIMATION,
    FOUNTAIN_OF_WATER_ANIMATION,
    HUMAN_KNIGHT_FEMALE_ATTACK_ANIMATION,
    HUMAN_KNIGHT_FEMALE_KICK_ANIMATION,
    HUMAN_KNIGHT_FEMALE_CAST_ANIMATION,
    HUMAN_KNIGHT_MALE_ATTACK_ANIMATION,
    HUMAN_KNIGHT_MALE_KICK_ANIMATION,
    HUMAN_PRIEST_MALE_LAWFUL_ATTACK_ANIMATION,
    HUMAN_PRIEST_MALE_LAWFUL_KICK_ANIMATION,
    HUMAN_PRIEST_MALE_LAWFUL_CAST_INDIR_ANIMATION,
    HUMAN_PRIEST_MALE_LAWFUL_CAST_DIR_ANIMATION,
    HUMAN_PRIEST_FEMALE_LAWFUL_ATTACK_ANIMATION,
    HUMAN_PRIEST_FEMALE_LAWFUL_KICK_ANIMATION,
    HUMAN_PRIEST_FEMALE_LAWFUL_CAST_INDIR_ANIMATION,
    HUMAN_PRIEST_FEMALE_LAWFUL_CAST_DIR_ANIMATION,
    HUMAN_PRIEST_MALE_NEUTRAL_ATTACK_ANIMATION,
    HUMAN_PRIEST_MALE_NEUTRAL_KICK_ANIMATION,
    HUMAN_PRIEST_MALE_NEUTRAL_CAST_INDIR_ANIMATION,
    HUMAN_PRIEST_MALE_NEUTRAL_CAST_DIR_ANIMATION,
    HUMAN_PRIEST_FEMALE_NEUTRAL_ATTACK_ANIMATION,
    HUMAN_PRIEST_FEMALE_NEUTRAL_KICK_ANIMATION,
    HUMAN_PRIEST_FEMALE_NEUTRAL_CAST_INDIR_ANIMATION,
    HUMAN_PRIEST_FEMALE_NEUTRAL_CAST_DIR_ANIMATION,
    HUMAN_PRIEST_MALE_CHAOTIC_ATTACK_ANIMATION,
    HUMAN_PRIEST_MALE_CHAOTIC_KICK_ANIMATION,
    HUMAN_PRIEST_MALE_CHAOTIC_CAST_INDIR_ANIMATION,
    HUMAN_PRIEST_MALE_CHAOTIC_CAST_DIR_ANIMATION,
    HUMAN_PRIEST_FEMALE_CHAOTIC_ATTACK_ANIMATION,
    HUMAN_PRIEST_FEMALE_CHAOTIC_KICK_ANIMATION,
    HUMAN_PRIEST_FEMALE_CHAOTIC_CAST_INDIR_ANIMATION,
    HUMAN_PRIEST_FEMALE_CHAOTIC_CAST_DIR_ANIMATION,
    GNOLL_PRIEST_MALE_LAWFUL_ATTACK_ANIMATION,
    GNOLL_PRIEST_MALE_LAWFUL_KICK_ANIMATION,
    GNOLL_PRIEST_MALE_LAWFUL_CAST_INDIR_ANIMATION,
    GNOLL_PRIEST_MALE_LAWFUL_CAST_DIR_ANIMATION,
    GNOLL_PRIEST_FEMALE_LAWFUL_ATTACK_ANIMATION,
    GNOLL_PRIEST_FEMALE_LAWFUL_KICK_ANIMATION,
    GNOLL_PRIEST_FEMALE_LAWFUL_CAST_INDIR_ANIMATION,
    GNOLL_PRIEST_FEMALE_LAWFUL_CAST_DIR_ANIMATION,
    GNOLL_PRIEST_MALE_NEUTRAL_ATTACK_ANIMATION,
    GNOLL_PRIEST_MALE_NEUTRAL_KICK_ANIMATION,
    GNOLL_PRIEST_MALE_NEUTRAL_CAST_INDIR_ANIMATION,
    GNOLL_PRIEST_MALE_NEUTRAL_CAST_DIR_ANIMATION,
    GNOLL_PRIEST_FEMALE_NEUTRAL_ATTACK_ANIMATION,
    GNOLL_PRIEST_FEMALE_NEUTRAL_KICK_ANIMATION,
    GNOLL_PRIEST_FEMALE_NEUTRAL_CAST_INDIR_ANIMATION,
    GNOLL_PRIEST_FEMALE_NEUTRAL_CAST_DIR_ANIMATION,
    GNOLL_PRIEST_MALE_CHAOTIC_ATTACK_ANIMATION,
    GNOLL_PRIEST_MALE_CHAOTIC_KICK_ANIMATION,
    GNOLL_PRIEST_MALE_CHAOTIC_CAST_INDIR_ANIMATION,
    GNOLL_PRIEST_MALE_CHAOTIC_CAST_DIR_ANIMATION,
    GNOLL_PRIEST_FEMALE_CHAOTIC_ATTACK_ANIMATION,
    GNOLL_PRIEST_FEMALE_CHAOTIC_KICK_ANIMATION,
    GNOLL_PRIEST_FEMALE_CHAOTIC_CAST_INDIR_ANIMATION,
    GNOLL_PRIEST_FEMALE_CHAOTIC_CAST_DIR_ANIMATION,
    ELF_PRIEST_MALE_LAWFUL_ATTACK_ANIMATION,
    ELF_PRIEST_MALE_LAWFUL_KICK_ANIMATION,
    ELF_PRIEST_MALE_LAWFUL_CAST_INDIR_ANIMATION,
    ELF_PRIEST_MALE_LAWFUL_CAST_DIR_ANIMATION,
    ELF_PRIEST_FEMALE_LAWFUL_ATTACK_ANIMATION,
    ELF_PRIEST_FEMALE_LAWFUL_KICK_ANIMATION,
    ELF_PRIEST_FEMALE_LAWFUL_CAST_INDIR_ANIMATION,
    ELF_PRIEST_FEMALE_LAWFUL_CAST_DIR_ANIMATION,
    ELF_PRIEST_MALE_NEUTRAL_ATTACK_ANIMATION,
    ELF_PRIEST_MALE_NEUTRAL_KICK_ANIMATION,
    ELF_PRIEST_MALE_NEUTRAL_CAST_INDIR_ANIMATION,
    ELF_PRIEST_MALE_NEUTRAL_CAST_DIR_ANIMATION,
    ELF_PRIEST_FEMALE_NEUTRAL_ATTACK_ANIMATION,
    ELF_PRIEST_FEMALE_NEUTRAL_KICK_ANIMATION,
    ELF_PRIEST_FEMALE_NEUTRAL_CAST_INDIR_ANIMATION,
    ELF_PRIEST_FEMALE_NEUTRAL_CAST_DIR_ANIMATION,
    ELF_PRIEST_MALE_CHAOTIC_ATTACK_ANIMATION,
    ELF_PRIEST_MALE_CHAOTIC_KICK_ANIMATION,
    ELF_PRIEST_MALE_CHAOTIC_CAST_INDIR_ANIMATION,
    ELF_PRIEST_MALE_CHAOTIC_CAST_DIR_ANIMATION,
    ELF_PRIEST_FEMALE_CHAOTIC_ATTACK_ANIMATION,
    ELF_PRIEST_FEMALE_CHAOTIC_KICK_ANIMATION,
    ELF_PRIEST_FEMALE_CHAOTIC_CAST_INDIR_ANIMATION,
    ELF_PRIEST_FEMALE_CHAOTIC_CAST_DIR_ANIMATION,
    DWARF_KNIGHT_FEMALE_ATTACK_ANIMATION,
    DWARF_KNIGHT_FEMALE_KICK_ANIMATION,
    DWARF_KNIGHT_MALE_ATTACK_ANIMATION,
    DWARF_KNIGHT_MALE_KICK_ANIMATION,
    ORC_BARBARIAN_MALE_ATTACK_ANIMATION,
    ORC_BARBARIAN_MALE_KICK_ANIMATION,
    ORC_BARBARIAN_FEMALE_ATTACK_ANIMATION,
    ORC_BARBARIAN_FEMALE_KICK_ANIMATION,
    ORC_ROGUE_FEMALE_ATTACK_ANIMATION,
    ORC_ROGUE_FEMALE_KICK_ANIMATION,
    ORC_ROGUE_MALE_ATTACK_ANIMATION,
    ORC_ROGUE_MALE_KICK_ANIMATION,
    HUMAN_ROGUE_FEMALE_ATTACK_ANIMATION,
    HUMAN_ROGUE_FEMALE_KICK_ANIMATION,
    HUMAN_ROGUE_MALE_ATTACK_ANIMATION,
    HUMAN_ROGUE_MALE_KICK_ANIMATION,
    GNOLL_ROGUE_FEMALE_ATTACK_ANIMATION,
    GNOLL_ROGUE_FEMALE_KICK_ANIMATION,
    GNOLL_ROGUE_MALE_ATTACK_ANIMATION,
    GNOLL_ROGUE_MALE_KICK_ANIMATION,
    HUMAN_TOURIST_MALE_ATTACK_ANIMATION,
    HUMAN_TOURIST_MALE_KICK_ANIMATION,
    HUMAN_TOURIST_FEMALE_ATTACK_ANIMATION,
    HUMAN_TOURIST_FEMALE_KICK_ANIMATION,
    HUMAN_BARBARIAN_MALE_ATTACK_ANIMATION,
    HUMAN_BARBARIAN_MALE_KICK_ANIMATION,
    HUMAN_BARBARIAN_FEMALE_ATTACK_ANIMATION,
    HUMAN_BARBARIAN_FEMALE_KICK_ANIMATION,
    GNOLL_BARBARIAN_MALE_ATTACK_ANIMATION,
    GNOLL_BARBARIAN_MALE_KICK_ANIMATION,
    GNOLL_BARBARIAN_FEMALE_ATTACK_ANIMATION,
    GNOLL_BARBARIAN_FEMALE_KICK_ANIMATION,
    HUMAN_VALKYRIE_FEMALE_ATTACK_ANIMATION,
    HUMAN_VALKYRIE_FEMALE_KICK_ANIMATION,
    DWARF_VALKYRIE_FEMALE_ATTACK_ANIMATION,
    DWARF_VALKYRIE_FEMALE_KICK_ANIMATION,
    ELF_RANGER_MALE_FIRE_ANIMATION,
    ELF_RANGER_MALE_KICK_ANIMATION,
    ELF_RANGER_FEMALE_FIRE_ANIMATION,
    ELF_RANGER_FEMALE_KICK_ANIMATION,
    HUMAN_RANGER_MALE_FIRE_ANIMATION,
    HUMAN_RANGER_MALE_KICK_ANIMATION,
    HUMAN_RANGER_FEMALE_FIRE_ANIMATION,
    HUMAN_RANGER_FEMALE_KICK_ANIMATION,
    ORC_RANGER_MALE_FIRE_ANIMATION,
    ORC_RANGER_MALE_KICK_ANIMATION,
    ORC_RANGER_FEMALE_FIRE_ANIMATION,
    ORC_RANGER_FEMALE_KICK_ANIMATION,
    GNOLL_RANGER_MALE_FIRE_ANIMATION,
    GNOLL_RANGER_MALE_KICK_ANIMATION,
    GNOLL_RANGER_FEMALE_FIRE_ANIMATION,
    GNOLL_RANGER_FEMALE_KICK_ANIMATION,
    GNOLL_HEALER_MALE_ATTACK_ANIMATION,
    GNOLL_HEALER_MALE_KICK_ANIMATION,
    GNOLL_HEALER_MALE_CAST_INDIR_ANIMATION,
    GNOLL_HEALER_MALE_CAST_DIR_ANIMATION,
    GNOLL_HEALER_FEMALE_ATTACK_ANIMATION,
    GNOLL_HEALER_FEMALE_KICK_ANIMATION,
    GNOLL_HEALER_FEMALE_CAST_INDIR_ANIMATION,
    GNOLL_HEALER_FEMALE_CAST_DIR_ANIMATION,
    HUMAN_HEALER_FEMALE_ATTACK_ANIMATION,
    HUMAN_HEALER_FEMALE_KICK_ANIMATION,
    HUMAN_HEALER_FEMALE_POTION_DRINK_ANIMATION,
    HUMAN_HEALER_FEMALE_CAST_DIR_ANIMATION,
    HUMAN_HEALER_FEMALE_CAST_INDIR_ANIMATION,
    HUMAN_HEALER_MALE_ATTACK_ANIMATION,
    HUMAN_HEALER_MALE_KICK_ANIMATION,
    HUMAN_HEALER_MALE_POTION_DRINK_ANIMATION,
    HUMAN_HEALER_MALE_CAST_DIR_ANIMATION,
    HUMAN_HEALER_MALE_CAST_INDIR_ANIMATION,
    HUMAN_MONK_MALE_ATTACK_ANIMATION,
    HUMAN_MONK_MALE_KICK_ANIMATION,
    HUMAN_MONK_MALE_CAST_INDIR_ANIMATION,
    HUMAN_MONK_MALE_CAST_DIR_ANIMATION,
    HUMAN_MONK_FEMALE_ATTACK_ANIMATION,
    HUMAN_MONK_FEMALE_KICK_ANIMATION,
    HUMAN_MONK_FEMALE_CAST_INDIR_ANIMATION,
    HUMAN_MONK_FEMALE_CAST_DIR_ANIMATION,
    HUMAN_SAMURAI_MALE_ATTACK_ANIMATION,
    HUMAN_SAMURAI_MALE_KICK_ANIMATION,
    HUMAN_SAMURAI_FEMALE_ATTACK_ANIMATION,
    HUMAN_SAMURAI_FEMALE_KICK_ANIMATION,
    HUMAN_WIZARD_MALE_ATTACK_ANIMATION,
    HUMAN_WIZARD_MALE_KICK_ANIMATION,
    HUMAN_WIZARD_MALE_CAST_INDIR_ANIMATION,
    HUMAN_WIZARD_MALE_CAST_DIR_ANIMATION,
    HUMAN_WIZARD_FEMALE_ATTACK_ANIMATION,
    HUMAN_WIZARD_FEMALE_KICK_ANIMATION,
    HUMAN_WIZARD_FEMALE_CAST_INDIR_ANIMATION,
    HUMAN_WIZARD_FEMALE_CAST_DIR_ANIMATION,
    ELF_WIZARD_MALE_ATTACK_ANIMATION,
    ELF_WIZARD_MALE_KICK_ANIMATION,
    ELF_WIZARD_MALE_CAST_INDIR_ANIMATION,
    ELF_WIZARD_MALE_CAST_DIR_ANIMATION,
    ELF_WIZARD_FEMALE_ATTACK_ANIMATION,
    ELF_WIZARD_FEMALE_KICK_ANIMATION,
    ELF_WIZARD_FEMALE_CAST_INDIR_ANIMATION,
    ELF_WIZARD_FEMALE_CAST_DIR_ANIMATION,
    ORC_WIZARD_MALE_ATTACK_ANIMATION,
    ORC_WIZARD_MALE_KICK_ANIMATION,
    ORC_WIZARD_MALE_CAST_INDIR_ANIMATION,
    ORC_WIZARD_MALE_CAST_DIR_ANIMATION,
    ORC_WIZARD_FEMALE_ATTACK_ANIMATION,
    ORC_WIZARD_FEMALE_KICK_ANIMATION,
    ORC_WIZARD_FEMALE_CAST_INDIR_ANIMATION,
    ORC_WIZARD_FEMALE_CAST_DIR_ANIMATION,
    DWARF_CAVEMAN_MALE_ATTACK_ANIMATION,
    DWARF_CAVEMAN_MALE_KICK_ANIMATION,
    DWARF_CAVEMAN_FEMALE_ATTACK_ANIMATION,
    DWARF_CAVEMAN_FEMALE_KICK_ANIMATION,
    HUMAN_CAVEMAN_MALE_ATTACK_ANIMATION,
    HUMAN_CAVEMAN_MALE_KICK_ANIMATION,
    HUMAN_CAVEMAN_FEMALE_ATTACK_ANIMATION,
    HUMAN_CAVEMAN_FEMALE_KICK_ANIMATION,
    GNOLL_CAVEMAN_MALE_ATTACK_ANIMATION,
    GNOLL_CAVEMAN_MALE_KICK_ANIMATION,
    GNOLL_CAVEMAN_FEMALE_ATTACK_ANIMATION,
    GNOLL_CAVEMAN_FEMALE_KICK_ANIMATION,
    DWARF_ARCHAEOLOGIST_MALE_ATTACK_ANIMATION,
    DWARF_ARCHAEOLOGIST_MALE_KICK_ANIMATION,
    DWARF_ARCHAEOLOGIST_FEMALE_ATTACK_ANIMATION,
    DWARF_ARCHAEOLOGIST_FEMALE_KICK_ANIMATION,
    HUMAN_ARCHAEOLOGIST_MALE_ATTACK_ANIMATION,
    HUMAN_ARCHAEOLOGIST_MALE_KICK_ANIMATION,
    HUMAN_ARCHAEOLOGIST_FEMALE_ATTACK_ANIMATION,
    HUMAN_ARCHAEOLOGIST_FEMALE_KICK_ANIMATION,
    OCHRE_JELLY_SWALLOW_ANIMATION,
    DUST_VORTEX_SWALLOW_ANIMATION,
    FOG_CLOUD_SWALLOW_ANIMATION,
    ICE_VORTEX_SWALLOW_ANIMATION,
    STEAM_VORTEX_SWALLOW_ANIMATION,
    FIRE_VORTEX_SWALLOW_ANIMATION,
    ENERGY_VORTEX_SWALLOW_ANIMATION,
    AIR_ELEMENTAL_SWALLOW_ANIMATION,
    ELDER_AIR_ELEMENTAL_SWALLOW_ANIMATION,
    JUIBLEX_SWALLOW_ANIMATION,
    FIERY_EXPLOSION_ANIMATION,
    MAGIC_EXPLOSION_ANIMATION,
    FROSTY_EXPLOSION_ANIMATION,
    NOXIOUS_EXPLOSION_ANIMATION,
    CIRCLE_OF_FIRE_ANIMATION,
    CIRCLE_OF_FROST_ANIMATION,
    CIRCLE_OF_LIGHTNING_ANIMATION,
    CIRCLE_OF_MAGIC_ANIMATION,
    CIRCLE_OF_RADIANCE_ANIMATION,
    SCROLL_OF_FIRE_ANIMATION,
    SCROLL_OF_EARTH_ANIMATION,
    FLAMING_SPHERE_EXPLOSION_ANIMATION,
    FREEZING_SPHERE_EXPLOSION_ANIMATION,
    SHOCKING_SPHERE_EXPLOSION_ANIMATION,
    METEOR_SWARM_ANIMATION,
    FIRE_RAY_ANIMATION,
    MAGIC_MISSILE_RAY_ANIMATION,
    LIGHTNING_RAY_ANIMATION,
    FROST_RAY_ANIMATION,
    SLEEP_RAY_ANIMATION,
    DISINTEGRATION_RAY_ANIMATION,
    PETRIFICATION_RAY_ANIMATION,
    DEATH_RAY_ANIMATION,
    FROST_BREATH_ANIMATION,
    FIRE_BREATH_ANIMATION,
    DIGGING_RAY_ANIMATION,
    GENERIC_SPELL_EFFECT_ANIMATION,
    TELEPORT_IN_ANIMATION,
    TELEPORT_OUT_ANIMATION,
    LEVEL_TELEPORT_IN_ANIMATION,
    LEVEL_TELEPORT_OUT_ANIMATION,
    SUMMON_DEMON_ANIMATION,
    SUMMON_CELESTIAL_ANIMATION,
    SLEEP_GAS_TRAP_EFFECT_ANIMATION,
    RUST_TRAP_EFFECT_ANIMATION,
    FIRE_TRAP_EFFECT_ANIMATION,
    PUFF_OF_SMOKE_ANIMATION,
    MAGIC_TRAP_EFFECT_ANIMATION,
    MAGIC_TRAP_LIGHT_FLASH_ANIMATION,
    ANTIMAGIC_TRAP_EFFECT_ANIMATION,
    POLYMORPH_TRAP_EFFECT_ANIMATION,
    FALLING_ROCK_TRAP_TRAP_DOOR_ANIMATION,
    FALLING_ROCK_TRAP_FALLING_ROCK_ANIMATION,
    LAND_MINE_EXPLOSION_ANIMATION,
    BEAR_TRAP_CLOSE_ANIMATION,
    BEAR_TRAP_OPEN_ANIMATION,
    SMALL_FIERY_EXPLOSION_ANIMATION,
    POISON_CLOUD_ANIMATION,
    TWISTED_CANDLE_LIT_ANIMATION,
    OLD_FASHIONED_CANDLE_LIT_ANIMATION,
    ORIENTAL_BRASS_LAMP_LIT_ANIMATION,
    ANTIQUATED_BRASS_LAMP_LIT_ANIMATION,
    VIBRATING_SQUARE_ANIMATION,
    CANDELABRUM_LIT_ANIMATION,
    LARGE_FIVE_BRANCHED_CANDELABRUM_LIT_ANIMATION,
    YELLOW_LIGHT_FLASH_ANIMATION,
    BLACK_LIGHT_FLASH_ANIMATION,
    BRAZIER_LIT_ANIMATION,
    BRAZIER_SUBTYPE_1_LIT_ANIMATION,
    BRAZIER_SUBTYPE_2_LIT_ANIMATION,
    ROCK_PIERCER_DROP_ANIMATION,
    MAX_ANIMATIONS
};

#define HANDCRAFTED_CANDLE_ANIMATION_FRAMES 5
#define HANDCRAFTED_CANDLE_ANIMATION_TILES 5
#define BRASS_LANTERN_LIT_ANIMATION_FRAMES 1
#define BRASS_LANTERN_LIT_ANIMATION_TILES 1
#define LAWFUL_ALTAR_ANIMATION_FRAMES 5
#define LAWFUL_ALTAR_ANIMATION_TILES 5
#define NEUTRAL_ALTAR_ANIMATION_FRAMES 4
#define NEUTRAL_ALTAR_ANIMATION_TILES 4
#define CHAOTIC_ALTAR_ANIMATION_FRAMES 4
#define CHAOTIC_ALTAR_ANIMATION_TILES 4
#define ALTAR_OF_MOLOCH_ANIMATION_FRAMES 5
#define ALTAR_OF_MOLOCH_ANIMATION_TILES 5
#define HIGH_ALTAR_ANIMATION_FRAMES 5
#define HIGH_ALTAR_ANIMATION_TILES 5
#define LAND_MINE_ACTIVATED_ANIMATION_FRAMES 1
#define LAND_MINE_ACTIVATED_ANIMATION_TILES 1
#define MAGIC_TRAP_STAND_ANIMATION_FRAMES 8
#define MAGIC_TRAP_STAND_ANIMATION_TILES 8
#define ANTIMAGIC_TRAP_STAND_ANIMATION_FRAMES 10
#define ANTIMAGIC_TRAP_STAND_ANIMATION_TILES 10
#define TELEPORT_TRAP_STAND_ANIMATION_FRAMES 9
#define TELEPORT_TRAP_STAND_ANIMATION_TILES 9
#define LEVEL_TELEPORT_TRAP_STAND_ANIMATION_FRAMES 9
#define LEVEL_TELEPORT_TRAP_STAND_ANIMATION_TILES 9
#define POLYMORPH_TRAP_STAND_ANIMATION_FRAMES 10
#define POLYMORPH_TRAP_STAND_ANIMATION_TILES 10
#define STATUE_TRAP_STAND_ANIMATION_FRAMES 10
#define STATUE_TRAP_STAND_ANIMATION_TILES 10
#define FIRE_TRAP_STAND_ANIMATION_FRAMES 1
#define FIRE_TRAP_STAND_ANIMATION_TILES 1
#define MAGIC_PORTAL_STAND_ANIMATION_FRAMES 9
#define MAGIC_PORTAL_STAND_ANIMATION_TILES 9
#define LOOK_CURSOR_ANIMATION_FRAMES 3
#define LOOK_CURSOR_ANIMATION_TILES 2
#define KOBOLD_ANIMATION_FRAMES 1
#define KOBOLD_ANIMATION_TILES 1
#define LARGE_KOBOLD_ANIMATION_FRAMES 1
#define LARGE_KOBOLD_ANIMATION_TILES 1
#define KOBOLD_LORD_ANIMATION_FRAMES 1
#define KOBOLD_LORD_ANIMATION_TILES 1
#define KOBOLD_SHAMAN_ANIMATION_FRAMES 1
#define KOBOLD_SHAMAN_ANIMATION_TILES 1
#define DRACOLICH_ATTACK_ANIMATION_FRAMES 4
#define DRACOLICH_ATTACK_ANIMATION_TILES 4
#define MAGIC_FOUNTAIN_ANIMATION_FRAMES 5
#define MAGIC_FOUNTAIN_ANIMATION_TILES 5
#define FOUNTAIN_OF_HEALING_ANIMATION_FRAMES 5
#define FOUNTAIN_OF_HEALING_ANIMATION_TILES 5
#define FOUNTAIN_OF_MANA_ANIMATION_FRAMES 5
#define FOUNTAIN_OF_MANA_ANIMATION_TILES 5
#define FOUNTAIN_OF_POWER_ANIMATION_FRAMES 5
#define FOUNTAIN_OF_POWER_ANIMATION_TILES 5
#define FOUNTAIN_OF_POISON_ANIMATION_FRAMES 5
#define FOUNTAIN_OF_POISON_ANIMATION_TILES 5
#define FOUNTAIN_OF_WATER_ANIMATION_FRAMES 5
#define FOUNTAIN_OF_WATER_ANIMATION_TILES 5
#define HUMAN_KNIGHT_FEMALE_ATTACK_ANIMATION_FRAMES 9
#define HUMAN_KNIGHT_FEMALE_ATTACK_ANIMATION_TILES 9
#define HUMAN_KNIGHT_FEMALE_KICK_ANIMATION_FRAMES 11
#define HUMAN_KNIGHT_FEMALE_KICK_ANIMATION_TILES 11
#define HUMAN_KNIGHT_FEMALE_CAST_ANIMATION_FRAMES 13
#define HUMAN_KNIGHT_FEMALE_CAST_ANIMATION_TILES 13
#define HUMAN_KNIGHT_MALE_ATTACK_ANIMATION_FRAMES 9
#define HUMAN_KNIGHT_MALE_ATTACK_ANIMATION_TILES 9
#define HUMAN_KNIGHT_MALE_KICK_ANIMATION_FRAMES 10
#define HUMAN_KNIGHT_MALE_KICK_ANIMATION_TILES 10

#define HUMAN_PRIEST_MALE_LAWFUL_ATTACK_ANIMATION_FRAMES 9
#define HUMAN_PRIEST_MALE_LAWFUL_ATTACK_ANIMATION_TILES 9
#define HUMAN_PRIEST_MALE_LAWFUL_KICK_ANIMATION_FRAMES 9
#define HUMAN_PRIEST_MALE_LAWFUL_KICK_ANIMATION_TILES 9
#define HUMAN_PRIEST_MALE_LAWFUL_CAST_INDIR_ANIMATION_FRAMES 10
#define HUMAN_PRIEST_MALE_LAWFUL_CAST_INDIR_ANIMATION_TILES 10
#define HUMAN_PRIEST_MALE_LAWFUL_CAST_DIR_ANIMATION_FRAMES 20
#define HUMAN_PRIEST_MALE_LAWFUL_CAST_DIR_ANIMATION_TILES 20
#define HUMAN_PRIEST_FEMALE_LAWFUL_ATTACK_ANIMATION_FRAMES 9
#define HUMAN_PRIEST_FEMALE_LAWFUL_ATTACK_ANIMATION_TILES 9
#define HUMAN_PRIEST_FEMALE_LAWFUL_KICK_ANIMATION_FRAMES 9
#define HUMAN_PRIEST_FEMALE_LAWFUL_KICK_ANIMATION_TILES 9
#define HUMAN_PRIEST_FEMALE_LAWFUL_CAST_INDIR_ANIMATION_FRAMES 10
#define HUMAN_PRIEST_FEMALE_LAWFUL_CAST_INDIR_ANIMATION_TILES 10
#define HUMAN_PRIEST_FEMALE_LAWFUL_CAST_DIR_ANIMATION_FRAMES 20
#define HUMAN_PRIEST_FEMALE_LAWFUL_CAST_DIR_ANIMATION_TILES 20

#define HUMAN_PRIEST_MALE_NEUTRAL_ATTACK_ANIMATION_FRAMES 9
#define HUMAN_PRIEST_MALE_NEUTRAL_ATTACK_ANIMATION_TILES 9
#define HUMAN_PRIEST_MALE_NEUTRAL_KICK_ANIMATION_FRAMES 9
#define HUMAN_PRIEST_MALE_NEUTRAL_KICK_ANIMATION_TILES 9
#define HUMAN_PRIEST_MALE_NEUTRAL_CAST_INDIR_ANIMATION_FRAMES 10
#define HUMAN_PRIEST_MALE_NEUTRAL_CAST_INDIR_ANIMATION_TILES 10
#define HUMAN_PRIEST_MALE_NEUTRAL_CAST_DIR_ANIMATION_FRAMES 20
#define HUMAN_PRIEST_MALE_NEUTRAL_CAST_DIR_ANIMATION_TILES 20
#define HUMAN_PRIEST_FEMALE_NEUTRAL_ATTACK_ANIMATION_FRAMES 9
#define HUMAN_PRIEST_FEMALE_NEUTRAL_ATTACK_ANIMATION_TILES 9
#define HUMAN_PRIEST_FEMALE_NEUTRAL_KICK_ANIMATION_FRAMES 9
#define HUMAN_PRIEST_FEMALE_NEUTRAL_KICK_ANIMATION_TILES 9
#define HUMAN_PRIEST_FEMALE_NEUTRAL_CAST_INDIR_ANIMATION_FRAMES 10
#define HUMAN_PRIEST_FEMALE_NEUTRAL_CAST_INDIR_ANIMATION_TILES 10
#define HUMAN_PRIEST_FEMALE_NEUTRAL_CAST_DIR_ANIMATION_FRAMES 20
#define HUMAN_PRIEST_FEMALE_NEUTRAL_CAST_DIR_ANIMATION_TILES 20

#define HUMAN_PRIEST_MALE_CHAOTIC_ATTACK_ANIMATION_FRAMES 9
#define HUMAN_PRIEST_MALE_CHAOTIC_ATTACK_ANIMATION_TILES 9
#define HUMAN_PRIEST_MALE_CHAOTIC_KICK_ANIMATION_FRAMES 9
#define HUMAN_PRIEST_MALE_CHAOTIC_KICK_ANIMATION_TILES 9
#define HUMAN_PRIEST_MALE_CHAOTIC_CAST_INDIR_ANIMATION_FRAMES 10
#define HUMAN_PRIEST_MALE_CHAOTIC_CAST_INDIR_ANIMATION_TILES 10
#define HUMAN_PRIEST_MALE_CHAOTIC_CAST_DIR_ANIMATION_FRAMES 20
#define HUMAN_PRIEST_MALE_CHAOTIC_CAST_DIR_ANIMATION_TILES 20
#define HUMAN_PRIEST_FEMALE_CHAOTIC_ATTACK_ANIMATION_FRAMES 9
#define HUMAN_PRIEST_FEMALE_CHAOTIC_ATTACK_ANIMATION_TILES 9
#define HUMAN_PRIEST_FEMALE_CHAOTIC_KICK_ANIMATION_FRAMES 9
#define HUMAN_PRIEST_FEMALE_CHAOTIC_KICK_ANIMATION_TILES 9
#define HUMAN_PRIEST_FEMALE_CHAOTIC_CAST_INDIR_ANIMATION_FRAMES 10
#define HUMAN_PRIEST_FEMALE_CHAOTIC_CAST_INDIR_ANIMATION_TILES 10
#define HUMAN_PRIEST_FEMALE_CHAOTIC_CAST_DIR_ANIMATION_FRAMES 20
#define HUMAN_PRIEST_FEMALE_CHAOTIC_CAST_DIR_ANIMATION_TILES 20

#define GNOLL_PRIEST_MALE_LAWFUL_ATTACK_ANIMATION_FRAMES 9
#define GNOLL_PRIEST_MALE_LAWFUL_ATTACK_ANIMATION_TILES 9
#define GNOLL_PRIEST_MALE_LAWFUL_KICK_ANIMATION_FRAMES 9
#define GNOLL_PRIEST_MALE_LAWFUL_KICK_ANIMATION_TILES 9
#define GNOLL_PRIEST_MALE_LAWFUL_CAST_INDIR_ANIMATION_FRAMES 10
#define GNOLL_PRIEST_MALE_LAWFUL_CAST_INDIR_ANIMATION_TILES 10
#define GNOLL_PRIEST_MALE_LAWFUL_CAST_DIR_ANIMATION_FRAMES 21
#define GNOLL_PRIEST_MALE_LAWFUL_CAST_DIR_ANIMATION_TILES 21
#define GNOLL_PRIEST_FEMALE_LAWFUL_ATTACK_ANIMATION_FRAMES 9
#define GNOLL_PRIEST_FEMALE_LAWFUL_ATTACK_ANIMATION_TILES 9
#define GNOLL_PRIEST_FEMALE_LAWFUL_KICK_ANIMATION_FRAMES 9
#define GNOLL_PRIEST_FEMALE_LAWFUL_KICK_ANIMATION_TILES 9
#define GNOLL_PRIEST_FEMALE_LAWFUL_CAST_INDIR_ANIMATION_FRAMES 10
#define GNOLL_PRIEST_FEMALE_LAWFUL_CAST_INDIR_ANIMATION_TILES 10
#define GNOLL_PRIEST_FEMALE_LAWFUL_CAST_DIR_ANIMATION_FRAMES 21
#define GNOLL_PRIEST_FEMALE_LAWFUL_CAST_DIR_ANIMATION_TILES 21

#define GNOLL_PRIEST_MALE_NEUTRAL_ATTACK_ANIMATION_FRAMES 9
#define GNOLL_PRIEST_MALE_NEUTRAL_ATTACK_ANIMATION_TILES 9
#define GNOLL_PRIEST_MALE_NEUTRAL_KICK_ANIMATION_FRAMES 9
#define GNOLL_PRIEST_MALE_NEUTRAL_KICK_ANIMATION_TILES 9
#define GNOLL_PRIEST_MALE_NEUTRAL_CAST_INDIR_ANIMATION_FRAMES 10
#define GNOLL_PRIEST_MALE_NEUTRAL_CAST_INDIR_ANIMATION_TILES 10
#define GNOLL_PRIEST_MALE_NEUTRAL_CAST_DIR_ANIMATION_FRAMES 21
#define GNOLL_PRIEST_MALE_NEUTRAL_CAST_DIR_ANIMATION_TILES 21
#define GNOLL_PRIEST_FEMALE_NEUTRAL_ATTACK_ANIMATION_FRAMES 9
#define GNOLL_PRIEST_FEMALE_NEUTRAL_ATTACK_ANIMATION_TILES 9
#define GNOLL_PRIEST_FEMALE_NEUTRAL_KICK_ANIMATION_FRAMES 9
#define GNOLL_PRIEST_FEMALE_NEUTRAL_KICK_ANIMATION_TILES 9
#define GNOLL_PRIEST_FEMALE_NEUTRAL_CAST_INDIR_ANIMATION_FRAMES 10
#define GNOLL_PRIEST_FEMALE_NEUTRAL_CAST_INDIR_ANIMATION_TILES 10
#define GNOLL_PRIEST_FEMALE_NEUTRAL_CAST_DIR_ANIMATION_FRAMES 21
#define GNOLL_PRIEST_FEMALE_NEUTRAL_CAST_DIR_ANIMATION_TILES 21

#define GNOLL_PRIEST_MALE_CHAOTIC_ATTACK_ANIMATION_FRAMES 9
#define GNOLL_PRIEST_MALE_CHAOTIC_ATTACK_ANIMATION_TILES 9
#define GNOLL_PRIEST_MALE_CHAOTIC_KICK_ANIMATION_FRAMES 9
#define GNOLL_PRIEST_MALE_CHAOTIC_KICK_ANIMATION_TILES 9
#define GNOLL_PRIEST_MALE_CHAOTIC_CAST_INDIR_ANIMATION_FRAMES 10
#define GNOLL_PRIEST_MALE_CHAOTIC_CAST_INDIR_ANIMATION_TILES 10
#define GNOLL_PRIEST_MALE_CHAOTIC_CAST_DIR_ANIMATION_FRAMES 21
#define GNOLL_PRIEST_MALE_CHAOTIC_CAST_DIR_ANIMATION_TILES 21
#define GNOLL_PRIEST_FEMALE_CHAOTIC_ATTACK_ANIMATION_FRAMES 9
#define GNOLL_PRIEST_FEMALE_CHAOTIC_ATTACK_ANIMATION_TILES 9
#define GNOLL_PRIEST_FEMALE_CHAOTIC_KICK_ANIMATION_FRAMES 9
#define GNOLL_PRIEST_FEMALE_CHAOTIC_KICK_ANIMATION_TILES 9
#define GNOLL_PRIEST_FEMALE_CHAOTIC_CAST_INDIR_ANIMATION_FRAMES 10
#define GNOLL_PRIEST_FEMALE_CHAOTIC_CAST_INDIR_ANIMATION_TILES 10
#define GNOLL_PRIEST_FEMALE_CHAOTIC_CAST_DIR_ANIMATION_FRAMES 21
#define GNOLL_PRIEST_FEMALE_CHAOTIC_CAST_DIR_ANIMATION_TILES 21

#define ELF_PRIEST_MALE_LAWFUL_ATTACK_ANIMATION_FRAMES 9
#define ELF_PRIEST_MALE_LAWFUL_ATTACK_ANIMATION_TILES 9
#define ELF_PRIEST_MALE_LAWFUL_KICK_ANIMATION_FRAMES 9
#define ELF_PRIEST_MALE_LAWFUL_KICK_ANIMATION_TILES 9
#define ELF_PRIEST_MALE_LAWFUL_CAST_INDIR_ANIMATION_FRAMES 10
#define ELF_PRIEST_MALE_LAWFUL_CAST_INDIR_ANIMATION_TILES 10
#define ELF_PRIEST_MALE_LAWFUL_CAST_DIR_ANIMATION_FRAMES 17
#define ELF_PRIEST_MALE_LAWFUL_CAST_DIR_ANIMATION_TILES 17
#define ELF_PRIEST_FEMALE_LAWFUL_ATTACK_ANIMATION_FRAMES 9
#define ELF_PRIEST_FEMALE_LAWFUL_ATTACK_ANIMATION_TILES 9
#define ELF_PRIEST_FEMALE_LAWFUL_KICK_ANIMATION_FRAMES 9
#define ELF_PRIEST_FEMALE_LAWFUL_KICK_ANIMATION_TILES 9
#define ELF_PRIEST_FEMALE_LAWFUL_CAST_INDIR_ANIMATION_FRAMES 10
#define ELF_PRIEST_FEMALE_LAWFUL_CAST_INDIR_ANIMATION_TILES 10
#define ELF_PRIEST_FEMALE_LAWFUL_CAST_DIR_ANIMATION_FRAMES 17
#define ELF_PRIEST_FEMALE_LAWFUL_CAST_DIR_ANIMATION_TILES 17

#define ELF_PRIEST_MALE_NEUTRAL_ATTACK_ANIMATION_FRAMES 9
#define ELF_PRIEST_MALE_NEUTRAL_ATTACK_ANIMATION_TILES 9
#define ELF_PRIEST_MALE_NEUTRAL_KICK_ANIMATION_FRAMES 9
#define ELF_PRIEST_MALE_NEUTRAL_KICK_ANIMATION_TILES 9
#define ELF_PRIEST_MALE_NEUTRAL_CAST_INDIR_ANIMATION_FRAMES 10
#define ELF_PRIEST_MALE_NEUTRAL_CAST_INDIR_ANIMATION_TILES 10
#define ELF_PRIEST_MALE_NEUTRAL_CAST_DIR_ANIMATION_FRAMES 17
#define ELF_PRIEST_MALE_NEUTRAL_CAST_DIR_ANIMATION_TILES 17
#define ELF_PRIEST_FEMALE_NEUTRAL_ATTACK_ANIMATION_FRAMES 9
#define ELF_PRIEST_FEMALE_NEUTRAL_ATTACK_ANIMATION_TILES 9
#define ELF_PRIEST_FEMALE_NEUTRAL_KICK_ANIMATION_FRAMES 9
#define ELF_PRIEST_FEMALE_NEUTRAL_KICK_ANIMATION_TILES 9
#define ELF_PRIEST_FEMALE_NEUTRAL_CAST_INDIR_ANIMATION_FRAMES 10
#define ELF_PRIEST_FEMALE_NEUTRAL_CAST_INDIR_ANIMATION_TILES 10
#define ELF_PRIEST_FEMALE_NEUTRAL_CAST_DIR_ANIMATION_FRAMES 17
#define ELF_PRIEST_FEMALE_NEUTRAL_CAST_DIR_ANIMATION_TILES 17

#define ELF_PRIEST_MALE_CHAOTIC_ATTACK_ANIMATION_FRAMES 9
#define ELF_PRIEST_MALE_CHAOTIC_ATTACK_ANIMATION_TILES 9
#define ELF_PRIEST_MALE_CHAOTIC_KICK_ANIMATION_FRAMES 9
#define ELF_PRIEST_MALE_CHAOTIC_KICK_ANIMATION_TILES 9
#define ELF_PRIEST_MALE_CHAOTIC_CAST_INDIR_ANIMATION_FRAMES 10
#define ELF_PRIEST_MALE_CHAOTIC_CAST_INDIR_ANIMATION_TILES 10
#define ELF_PRIEST_MALE_CHAOTIC_CAST_DIR_ANIMATION_FRAMES 16
#define ELF_PRIEST_MALE_CHAOTIC_CAST_DIR_ANIMATION_TILES 16

#define ELF_PRIEST_FEMALE_CHAOTIC_ATTACK_ANIMATION_FRAMES 9
#define ELF_PRIEST_FEMALE_CHAOTIC_ATTACK_ANIMATION_TILES 9
#define ELF_PRIEST_FEMALE_CHAOTIC_KICK_ANIMATION_FRAMES 9
#define ELF_PRIEST_FEMALE_CHAOTIC_KICK_ANIMATION_TILES 9
#define ELF_PRIEST_FEMALE_CHAOTIC_CAST_INDIR_ANIMATION_FRAMES 10
#define ELF_PRIEST_FEMALE_CHAOTIC_CAST_INDIR_ANIMATION_TILES 10
#define ELF_PRIEST_FEMALE_CHAOTIC_CAST_DIR_ANIMATION_FRAMES 17
#define ELF_PRIEST_FEMALE_CHAOTIC_CAST_DIR_ANIMATION_TILES 17

#define DWARF_KNIGHT_FEMALE_ATTACK_ANIMATION_FRAMES 10
#define DWARF_KNIGHT_FEMALE_ATTACK_ANIMATION_TILES 10
#define DWARF_KNIGHT_FEMALE_KICK_ANIMATION_FRAMES 9
#define DWARF_KNIGHT_FEMALE_KICK_ANIMATION_TILES 9
#define DWARF_KNIGHT_MALE_ATTACK_ANIMATION_FRAMES 10
#define DWARF_KNIGHT_MALE_ATTACK_ANIMATION_TILES 10
#define DWARF_KNIGHT_MALE_KICK_ANIMATION_FRAMES 9
#define DWARF_KNIGHT_MALE_KICK_ANIMATION_TILES 9
#define ORC_BARBARIAN_MALE_ATTACK_ANIMATION_FRAMES 10
#define ORC_BARBARIAN_MALE_ATTACK_ANIMATION_TILES 10
#define ORC_BARBARIAN_MALE_KICK_ANIMATION_FRAMES 10
#define ORC_BARBARIAN_MALE_KICK_ANIMATION_TILES 10
#define ORC_BARBARIAN_FEMALE_ATTACK_ANIMATION_FRAMES 10
#define ORC_BARBARIAN_FEMALE_ATTACK_ANIMATION_TILES 10
#define ORC_BARBARIAN_FEMALE_KICK_ANIMATION_FRAMES 10
#define ORC_BARBARIAN_FEMALE_KICK_ANIMATION_TILES 10
#define ORC_ROGUE_FEMALE_ATTACK_ANIMATION_FRAMES 9
#define ORC_ROGUE_FEMALE_ATTACK_ANIMATION_TILES 9
#define ORC_ROGUE_FEMALE_KICK_ANIMATION_FRAMES 9
#define ORC_ROGUE_FEMALE_KICK_ANIMATION_TILES 9
#define ORC_ROGUE_MALE_ATTACK_ANIMATION_FRAMES 10
#define ORC_ROGUE_MALE_ATTACK_ANIMATION_TILES 10
#define ORC_ROGUE_MALE_KICK_ANIMATION_FRAMES 9
#define ORC_ROGUE_MALE_KICK_ANIMATION_TILES 9
#define HUMAN_ROGUE_FEMALE_ATTACK_ANIMATION_FRAMES 10
#define HUMAN_ROGUE_FEMALE_ATTACK_ANIMATION_TILES 10
#define HUMAN_ROGUE_FEMALE_KICK_ANIMATION_FRAMES 9
#define HUMAN_ROGUE_FEMALE_KICK_ANIMATION_TILES 9
#define HUMAN_ROGUE_MALE_ATTACK_ANIMATION_FRAMES 10
#define HUMAN_ROGUE_MALE_ATTACK_ANIMATION_TILES 10
#define HUMAN_ROGUE_MALE_KICK_ANIMATION_FRAMES 9
#define HUMAN_ROGUE_MALE_KICK_ANIMATION_TILES 9
#define GNOLL_ROGUE_FEMALE_ATTACK_ANIMATION_FRAMES 10
#define GNOLL_ROGUE_FEMALE_ATTACK_ANIMATION_TILES 10
#define GNOLL_ROGUE_FEMALE_KICK_ANIMATION_FRAMES 9
#define GNOLL_ROGUE_FEMALE_KICK_ANIMATION_TILES 9
#define GNOLL_ROGUE_MALE_ATTACK_ANIMATION_FRAMES 10
#define GNOLL_ROGUE_MALE_ATTACK_ANIMATION_TILES 10
#define GNOLL_ROGUE_MALE_KICK_ANIMATION_FRAMES 9
#define GNOLL_ROGUE_MALE_KICK_ANIMATION_TILES 9
#define HUMAN_TOURIST_MALE_ATTACK_ANIMATION_FRAMES 11
#define HUMAN_TOURIST_MALE_ATTACK_ANIMATION_TILES 11
#define HUMAN_TOURIST_MALE_KICK_ANIMATION_FRAMES 9
#define HUMAN_TOURIST_MALE_KICK_ANIMATION_TILES 9
#define HUMAN_TOURIST_FEMALE_ATTACK_ANIMATION_FRAMES 11
#define HUMAN_TOURIST_FEMALE_ATTACK_ANIMATION_TILES 11
#define HUMAN_TOURIST_FEMALE_KICK_ANIMATION_FRAMES 9
#define HUMAN_TOURIST_FEMALE_KICK_ANIMATION_TILES 9
#define HUMAN_BARBARIAN_MALE_ATTACK_ANIMATION_FRAMES 10
#define HUMAN_BARBARIAN_MALE_ATTACK_ANIMATION_TILES 10
#define HUMAN_BARBARIAN_MALE_KICK_ANIMATION_FRAMES 10
#define HUMAN_BARBARIAN_MALE_KICK_ANIMATION_TILES 10
#define HUMAN_BARBARIAN_FEMALE_ATTACK_ANIMATION_FRAMES 10
#define HUMAN_BARBARIAN_FEMALE_ATTACK_ANIMATION_TILES 10
#define HUMAN_BARBARIAN_FEMALE_KICK_ANIMATION_FRAMES 10
#define HUMAN_BARBARIAN_FEMALE_KICK_ANIMATION_TILES 10
#define GNOLL_BARBARIAN_MALE_ATTACK_ANIMATION_FRAMES 11
#define GNOLL_BARBARIAN_MALE_ATTACK_ANIMATION_TILES 11
#define GNOLL_BARBARIAN_MALE_KICK_ANIMATION_FRAMES 9
#define GNOLL_BARBARIAN_MALE_KICK_ANIMATION_TILES 9
#define GNOLL_BARBARIAN_FEMALE_ATTACK_ANIMATION_FRAMES 10
#define GNOLL_BARBARIAN_FEMALE_ATTACK_ANIMATION_TILES 10
#define GNOLL_BARBARIAN_FEMALE_KICK_ANIMATION_FRAMES 9
#define GNOLL_BARBARIAN_FEMALE_KICK_ANIMATION_TILES 9
#define HUMAN_VALKYRIE_FEMALE_ATTACK_ANIMATION_FRAMES 9
#define HUMAN_VALKYRIE_FEMALE_ATTACK_ANIMATION_TILES 9
#define HUMAN_VALKYRIE_FEMALE_KICK_ANIMATION_FRAMES 10
#define HUMAN_VALKYRIE_FEMALE_KICK_ANIMATION_TILES 10
#define DWARF_VALKYRIE_FEMALE_ATTACK_ANIMATION_FRAMES 9
#define DWARF_VALKYRIE_FEMALE_ATTACK_ANIMATION_TILES 9
#define DWARF_VALKYRIE_FEMALE_KICK_ANIMATION_FRAMES 10
#define DWARF_VALKYRIE_FEMALE_KICK_ANIMATION_TILES 10
#define ELF_RANGER_MALE_FIRE_ANIMATION_FRAMES 22
#define ELF_RANGER_MALE_FIRE_ANIMATION_TILES 22
#define ELF_RANGER_MALE_KICK_ANIMATION_FRAMES 10
#define ELF_RANGER_MALE_KICK_ANIMATION_TILES 10
#define ELF_RANGER_FEMALE_FIRE_ANIMATION_FRAMES 22
#define ELF_RANGER_FEMALE_FIRE_ANIMATION_TILES 22
#define ELF_RANGER_FEMALE_KICK_ANIMATION_FRAMES 10
#define ELF_RANGER_FEMALE_KICK_ANIMATION_TILES 10
#define HUMAN_RANGER_MALE_FIRE_ANIMATION_FRAMES 22
#define HUMAN_RANGER_MALE_FIRE_ANIMATION_TILES 22
#define HUMAN_RANGER_MALE_KICK_ANIMATION_FRAMES 10
#define HUMAN_RANGER_MALE_KICK_ANIMATION_TILES 10
#define HUMAN_RANGER_FEMALE_FIRE_ANIMATION_FRAMES 22
#define HUMAN_RANGER_FEMALE_FIRE_ANIMATION_TILES 22
#define HUMAN_RANGER_FEMALE_KICK_ANIMATION_FRAMES 10
#define HUMAN_RANGER_FEMALE_KICK_ANIMATION_TILES 10
#define ORC_RANGER_MALE_FIRE_ANIMATION_FRAMES 21
#define ORC_RANGER_MALE_FIRE_ANIMATION_TILES 21
#define ORC_RANGER_MALE_KICK_ANIMATION_FRAMES 11
#define ORC_RANGER_MALE_KICK_ANIMATION_TILES 11
#define ORC_RANGER_FEMALE_FIRE_ANIMATION_FRAMES 22
#define ORC_RANGER_FEMALE_FIRE_ANIMATION_TILES 22
#define ORC_RANGER_FEMALE_KICK_ANIMATION_FRAMES 11
#define ORC_RANGER_FEMALE_KICK_ANIMATION_TILES 11
#define GNOLL_RANGER_MALE_FIRE_ANIMATION_FRAMES 21
#define GNOLL_RANGER_MALE_FIRE_ANIMATION_TILES 21
#define GNOLL_RANGER_MALE_KICK_ANIMATION_FRAMES 9
#define GNOLL_RANGER_MALE_KICK_ANIMATION_TILES 9
#define GNOLL_RANGER_FEMALE_FIRE_ANIMATION_FRAMES 21
#define GNOLL_RANGER_FEMALE_FIRE_ANIMATION_TILES 21
#define GNOLL_RANGER_FEMALE_KICK_ANIMATION_FRAMES 9
#define GNOLL_RANGER_FEMALE_KICK_ANIMATION_TILES 9
#define GNOLL_HEALER_MALE_ATTACK_ANIMATION_FRAMES 9
#define GNOLL_HEALER_MALE_ATTACK_ANIMATION_TILES 9
#define GNOLL_HEALER_MALE_KICK_ANIMATION_FRAMES 9
#define GNOLL_HEALER_MALE_KICK_ANIMATION_TILES 9
#define GNOLL_HEALER_MALE_CAST_INDIR_ANIMATION_FRAMES 10
#define GNOLL_HEALER_MALE_CAST_INDIR_ANIMATION_TILES 10
#define GNOLL_HEALER_MALE_CAST_DIR_ANIMATION_FRAMES 12
#define GNOLL_HEALER_MALE_CAST_DIR_ANIMATION_TILES 12
#define GNOLL_HEALER_FEMALE_ATTACK_ANIMATION_FRAMES 10
#define GNOLL_HEALER_FEMALE_ATTACK_ANIMATION_TILES 10
#define GNOLL_HEALER_FEMALE_KICK_ANIMATION_FRAMES 9
#define GNOLL_HEALER_FEMALE_KICK_ANIMATION_TILES 9
#define GNOLL_HEALER_FEMALE_CAST_INDIR_ANIMATION_FRAMES 10
#define GNOLL_HEALER_FEMALE_CAST_INDIR_ANIMATION_TILES 10
#define GNOLL_HEALER_FEMALE_CAST_DIR_ANIMATION_FRAMES 12
#define GNOLL_HEALER_FEMALE_CAST_DIR_ANIMATION_TILES 12
#define HUMAN_HEALER_FEMALE_ATTACK_ANIMATION_FRAMES 10
#define HUMAN_HEALER_FEMALE_ATTACK_ANIMATION_TILES 10
#define HUMAN_HEALER_FEMALE_KICK_ANIMATION_FRAMES 10
#define HUMAN_HEALER_FEMALE_KICK_ANIMATION_TILES 10
#define HUMAN_HEALER_FEMALE_POTION_DRINK_ANIMATION_FRAMES 16
#define HUMAN_HEALER_FEMALE_POTION_DRINK_ANIMATION_TILES 20
#define HUMAN_HEALER_FEMALE_CAST_DIR_ANIMATION_FRAMES 22
#define HUMAN_HEALER_FEMALE_CAST_DIR_ANIMATION_TILES 24
#define HUMAN_HEALER_FEMALE_CAST_INDIR_ANIMATION_FRAMES 21
#define HUMAN_HEALER_FEMALE_CAST_INDIR_ANIMATION_TILES 23
#define HUMAN_HEALER_MALE_ATTACK_ANIMATION_FRAMES 10
#define HUMAN_HEALER_MALE_ATTACK_ANIMATION_TILES 10
#define HUMAN_HEALER_MALE_KICK_ANIMATION_FRAMES 10
#define HUMAN_HEALER_MALE_KICK_ANIMATION_TILES 10
#define HUMAN_HEALER_MALE_POTION_DRINK_ANIMATION_FRAMES 16
#define HUMAN_HEALER_MALE_POTION_DRINK_ANIMATION_TILES 20
#define HUMAN_HEALER_MALE_CAST_DIR_ANIMATION_FRAMES 22
#define HUMAN_HEALER_MALE_CAST_DIR_ANIMATION_TILES 24
#define HUMAN_HEALER_MALE_CAST_INDIR_ANIMATION_FRAMES 21
#define HUMAN_HEALER_MALE_CAST_INDIR_ANIMATION_TILES 23
#define HUMAN_MONK_MALE_ATTACK_ANIMATION_FRAMES 10
#define HUMAN_MONK_MALE_ATTACK_ANIMATION_TILES 10
#define HUMAN_MONK_MALE_KICK_ANIMATION_FRAMES 9
#define HUMAN_MONK_MALE_KICK_ANIMATION_TILES 9
#define HUMAN_MONK_MALE_CAST_INDIR_ANIMATION_FRAMES 14
#define HUMAN_MONK_MALE_CAST_INDIR_ANIMATION_TILES 14
#define HUMAN_MONK_MALE_CAST_DIR_ANIMATION_FRAMES 10
#define HUMAN_MONK_MALE_CAST_DIR_ANIMATION_TILES 10
#define HUMAN_MONK_FEMALE_ATTACK_ANIMATION_FRAMES 10
#define HUMAN_MONK_FEMALE_ATTACK_ANIMATION_TILES 10
#define HUMAN_MONK_FEMALE_KICK_ANIMATION_FRAMES 9
#define HUMAN_MONK_FEMALE_KICK_ANIMATION_TILES 9
#define HUMAN_MONK_FEMALE_CAST_INDIR_ANIMATION_FRAMES 14
#define HUMAN_MONK_FEMALE_CAST_INDIR_ANIMATION_TILES 14
#define HUMAN_MONK_FEMALE_CAST_DIR_ANIMATION_FRAMES 10
#define HUMAN_MONK_FEMALE_CAST_DIR_ANIMATION_TILES 10
#define HUMAN_SAMURAI_MALE_ATTACK_ANIMATION_FRAMES 10
#define HUMAN_SAMURAI_MALE_ATTACK_ANIMATION_TILES 10
#define HUMAN_SAMURAI_MALE_KICK_ANIMATION_FRAMES 10
#define HUMAN_SAMURAI_MALE_KICK_ANIMATION_TILES 10
#define HUMAN_SAMURAI_FEMALE_ATTACK_ANIMATION_FRAMES 10
#define HUMAN_SAMURAI_FEMALE_ATTACK_ANIMATION_TILES 10
#define HUMAN_SAMURAI_FEMALE_KICK_ANIMATION_FRAMES 10
#define HUMAN_SAMURAI_FEMALE_KICK_ANIMATION_TILES 10
#define HUMAN_WIZARD_MALE_ATTACK_ANIMATION_FRAMES 9
#define HUMAN_WIZARD_MALE_ATTACK_ANIMATION_TILES 9
#define HUMAN_WIZARD_MALE_KICK_ANIMATION_FRAMES 10
#define HUMAN_WIZARD_MALE_KICK_ANIMATION_TILES 10
#define HUMAN_WIZARD_MALE_CAST_INDIR_ANIMATION_FRAMES 10
#define HUMAN_WIZARD_MALE_CAST_INDIR_ANIMATION_TILES 10
#define HUMAN_WIZARD_MALE_CAST_DIR_ANIMATION_FRAMES 19
#define HUMAN_WIZARD_MALE_CAST_DIR_ANIMATION_TILES 19
#define HUMAN_WIZARD_FEMALE_ATTACK_ANIMATION_FRAMES 9
#define HUMAN_WIZARD_FEMALE_ATTACK_ANIMATION_TILES 9
#define HUMAN_WIZARD_FEMALE_KICK_ANIMATION_FRAMES 10
#define HUMAN_WIZARD_FEMALE_KICK_ANIMATION_TILES 10
#define HUMAN_WIZARD_FEMALE_CAST_INDIR_ANIMATION_FRAMES 10
#define HUMAN_WIZARD_FEMALE_CAST_INDIR_ANIMATION_TILES 10
#define HUMAN_WIZARD_FEMALE_CAST_DIR_ANIMATION_FRAMES 18
#define HUMAN_WIZARD_FEMALE_CAST_DIR_ANIMATION_TILES 18
#define ELF_WIZARD_MALE_ATTACK_ANIMATION_FRAMES 9
#define ELF_WIZARD_MALE_ATTACK_ANIMATION_TILES 9
#define ELF_WIZARD_MALE_KICK_ANIMATION_FRAMES 10
#define ELF_WIZARD_MALE_KICK_ANIMATION_TILES 10
#define ELF_WIZARD_MALE_CAST_INDIR_ANIMATION_FRAMES 10
#define ELF_WIZARD_MALE_CAST_INDIR_ANIMATION_TILES 10
#define ELF_WIZARD_MALE_CAST_DIR_ANIMATION_FRAMES 20
#define ELF_WIZARD_MALE_CAST_DIR_ANIMATION_TILES 20
#define ELF_WIZARD_FEMALE_ATTACK_ANIMATION_FRAMES 9
#define ELF_WIZARD_FEMALE_ATTACK_ANIMATION_TILES 9
#define ELF_WIZARD_FEMALE_KICK_ANIMATION_FRAMES 10
#define ELF_WIZARD_FEMALE_KICK_ANIMATION_TILES 10
#define ELF_WIZARD_FEMALE_CAST_INDIR_ANIMATION_FRAMES 10
#define ELF_WIZARD_FEMALE_CAST_INDIR_ANIMATION_TILES 10
#define ELF_WIZARD_FEMALE_CAST_DIR_ANIMATION_FRAMES 20
#define ELF_WIZARD_FEMALE_CAST_DIR_ANIMATION_TILES 20
#define ORC_WIZARD_MALE_ATTACK_ANIMATION_FRAMES 10
#define ORC_WIZARD_MALE_ATTACK_ANIMATION_TILES 10
#define ORC_WIZARD_MALE_KICK_ANIMATION_FRAMES 9
#define ORC_WIZARD_MALE_KICK_ANIMATION_TILES 9
#define ORC_WIZARD_MALE_CAST_INDIR_ANIMATION_FRAMES 11
#define ORC_WIZARD_MALE_CAST_INDIR_ANIMATION_TILES 11
#define ORC_WIZARD_MALE_CAST_DIR_ANIMATION_FRAMES 19
#define ORC_WIZARD_MALE_CAST_DIR_ANIMATION_TILES 19
#define ORC_WIZARD_FEMALE_ATTACK_ANIMATION_FRAMES 10
#define ORC_WIZARD_FEMALE_ATTACK_ANIMATION_TILES 10
#define ORC_WIZARD_FEMALE_KICK_ANIMATION_FRAMES 9
#define ORC_WIZARD_FEMALE_KICK_ANIMATION_TILES 9
#define ORC_WIZARD_FEMALE_CAST_INDIR_ANIMATION_FRAMES 11
#define ORC_WIZARD_FEMALE_CAST_INDIR_ANIMATION_TILES 11
#define ORC_WIZARD_FEMALE_CAST_DIR_ANIMATION_FRAMES 19
#define ORC_WIZARD_FEMALE_CAST_DIR_ANIMATION_TILES 19
#define DWARF_CAVEMAN_MALE_ATTACK_ANIMATION_FRAMES 10
#define DWARF_CAVEMAN_MALE_ATTACK_ANIMATION_TILES 10
#define DWARF_CAVEMAN_MALE_KICK_ANIMATION_FRAMES 9
#define DWARF_CAVEMAN_MALE_KICK_ANIMATION_TILES 9
#define DWARF_CAVEMAN_FEMALE_ATTACK_ANIMATION_FRAMES 10
#define DWARF_CAVEMAN_FEMALE_ATTACK_ANIMATION_TILES 10
#define DWARF_CAVEMAN_FEMALE_KICK_ANIMATION_FRAMES 10
#define DWARF_CAVEMAN_FEMALE_KICK_ANIMATION_TILES 10
#define HUMAN_CAVEMAN_MALE_ATTACK_ANIMATION_FRAMES 10
#define HUMAN_CAVEMAN_MALE_ATTACK_ANIMATION_TILES 10
#define HUMAN_CAVEMAN_MALE_KICK_ANIMATION_FRAMES 10
#define HUMAN_CAVEMAN_MALE_KICK_ANIMATION_TILES 10
#define HUMAN_CAVEMAN_FEMALE_ATTACK_ANIMATION_FRAMES 10
#define HUMAN_CAVEMAN_FEMALE_ATTACK_ANIMATION_TILES 10
#define HUMAN_CAVEMAN_FEMALE_KICK_ANIMATION_FRAMES 10
#define HUMAN_CAVEMAN_FEMALE_KICK_ANIMATION_TILES 10
#define GNOLL_CAVEMAN_MALE_ATTACK_ANIMATION_FRAMES 9
#define GNOLL_CAVEMAN_MALE_ATTACK_ANIMATION_TILES 9
#define GNOLL_CAVEMAN_MALE_KICK_ANIMATION_FRAMES 9
#define GNOLL_CAVEMAN_MALE_KICK_ANIMATION_TILES 9
#define GNOLL_CAVEMAN_FEMALE_ATTACK_ANIMATION_FRAMES 9
#define GNOLL_CAVEMAN_FEMALE_ATTACK_ANIMATION_TILES 9
#define GNOLL_CAVEMAN_FEMALE_KICK_ANIMATION_FRAMES 9
#define GNOLL_CAVEMAN_FEMALE_KICK_ANIMATION_TILES 9
#define DWARF_ARCHAEOLOGIST_MALE_ATTACK_ANIMATION_FRAMES 10
#define DWARF_ARCHAEOLOGIST_MALE_ATTACK_ANIMATION_TILES 10
#define DWARF_ARCHAEOLOGIST_MALE_KICK_ANIMATION_FRAMES 9
#define DWARF_ARCHAEOLOGIST_MALE_KICK_ANIMATION_TILES 9
#define DWARF_ARCHAEOLOGIST_FEMALE_ATTACK_ANIMATION_FRAMES 10
#define DWARF_ARCHAEOLOGIST_FEMALE_ATTACK_ANIMATION_TILES 10
#define DWARF_ARCHAEOLOGIST_FEMALE_KICK_ANIMATION_FRAMES 9
#define DWARF_ARCHAEOLOGIST_FEMALE_KICK_ANIMATION_TILES 9
#define HUMAN_ARCHAEOLOGIST_MALE_ATTACK_ANIMATION_FRAMES 9
#define HUMAN_ARCHAEOLOGIST_MALE_ATTACK_ANIMATION_TILES 9
#define HUMAN_ARCHAEOLOGIST_MALE_KICK_ANIMATION_FRAMES 9
#define HUMAN_ARCHAEOLOGIST_MALE_KICK_ANIMATION_TILES 9
#define HUMAN_ARCHAEOLOGIST_FEMALE_ATTACK_ANIMATION_FRAMES 10
#define HUMAN_ARCHAEOLOGIST_FEMALE_ATTACK_ANIMATION_TILES 10
#define HUMAN_ARCHAEOLOGIST_FEMALE_KICK_ANIMATION_FRAMES 9
#define HUMAN_ARCHAEOLOGIST_FEMALE_KICK_ANIMATION_TILES 9
#define OCHRE_JELLY_SWALLOW_ANIMATION_FRAMES 1
#define OCHRE_JELLY_SWALLOW_ANIMATION_TILES 1 
#define DUST_VORTEX_SWALLOW_ANIMATION_FRAMES 3
#define DUST_VORTEX_SWALLOW_ANIMATION_TILES 3 
#define FOG_CLOUD_SWALLOW_ANIMATION_FRAMES 3
#define FOG_CLOUD_SWALLOW_ANIMATION_TILES 3 
#define ICE_VORTEX_SWALLOW_ANIMATION_FRAMES 3
#define ICE_VORTEX_SWALLOW_ANIMATION_TILES 3 
#define STEAM_VORTEX_SWALLOW_ANIMATION_FRAMES 3
#define STEAM_VORTEX_SWALLOW_ANIMATION_TILES 3 
#define FIRE_VORTEX_SWALLOW_ANIMATION_FRAMES 3
#define FIRE_VORTEX_SWALLOW_ANIMATION_TILES 3 
#define ENERGY_VORTEX_SWALLOW_ANIMATION_FRAMES 3
#define ENERGY_VORTEX_SWALLOW_ANIMATION_TILES 3 
#define AIR_ELEMENTAL_SWALLOW_ANIMATION_FRAMES 3
#define AIR_ELEMENTAL_SWALLOW_ANIMATION_TILES 3 
#define ELDER_AIR_ELEMENTAL_SWALLOW_ANIMATION_FRAMES 3
#define ELDER_AIR_ELEMENTAL_SWALLOW_ANIMATION_TILES 3 
#define JUIBLEX_SWALLOW_ANIMATION_FRAMES 1
#define JUIBLEX_SWALLOW_ANIMATION_TILES 1 
#define FIERY_EXPLOSION_ANIMATION_FRAMES 7
#define FIERY_EXPLOSION_ANIMATION_TILES 7 
#define MAGIC_EXPLOSION_ANIMATION_FRAMES 8
#define MAGIC_EXPLOSION_ANIMATION_TILES 8
#define FROSTY_EXPLOSION_ANIMATION_FRAMES 8
#define FROSTY_EXPLOSION_ANIMATION_TILES 8
#define NOXIOUS_EXPLOSION_ANIMATION_FRAMES 11
#define NOXIOUS_EXPLOSION_ANIMATION_TILES 11
#define CIRCLE_OF_FIRE_ANIMATION_FRAMES 24
#define CIRCLE_OF_FIRE_ANIMATION_TILES 16 
#define CIRCLE_OF_FROST_ANIMATION_FRAMES 25
#define CIRCLE_OF_FROST_ANIMATION_TILES 18 
#define CIRCLE_OF_LIGHTNING_ANIMATION_FRAMES 22
#define CIRCLE_OF_LIGHTNING_ANIMATION_TILES 14 
#define CIRCLE_OF_MAGIC_ANIMATION_FRAMES 29
#define CIRCLE_OF_MAGIC_ANIMATION_TILES 29 
#define CIRCLE_OF_RADIANCE_ANIMATION_FRAMES 22
#define CIRCLE_OF_RADIANCE_ANIMATION_TILES 22 
#define SCROLL_OF_FIRE_ANIMATION_FRAMES 24
#define SCROLL_OF_FIRE_ANIMATION_TILES 16 
#define SCROLL_OF_EARTH_ANIMATION_FRAMES 25
#define SCROLL_OF_EARTH_ANIMATION_TILES 21 
#define FLAMING_SPHERE_EXPLOSION_ANIMATION_FRAMES 12
#define FLAMING_SPHERE_EXPLOSION_ANIMATION_TILES 12 
#define FREEZING_SPHERE_EXPLOSION_ANIMATION_FRAMES 10
#define FREEZING_SPHERE_EXPLOSION_ANIMATION_TILES 10 
#define SHOCKING_SPHERE_EXPLOSION_ANIMATION_FRAMES 14
#define SHOCKING_SPHERE_EXPLOSION_ANIMATION_TILES 14 
#define FIRE_RAY_ANIMATION_FRAMES 17
#define FIRE_RAY_ANIMATION_TILES 11
#define MAGIC_MISSILE_RAY_ANIMATION_FRAMES 5
#define MAGIC_MISSILE_RAY_ANIMATION_TILES 9
#define LIGHTNING_RAY_ANIMATION_FRAMES 12
#define LIGHTNING_RAY_ANIMATION_TILES 10
#define FROST_RAY_ANIMATION_FRAMES 10
#define FROST_RAY_ANIMATION_TILES 10
#define SLEEP_RAY_ANIMATION_FRAMES 13
#define SLEEP_RAY_ANIMATION_TILES 13
#define DISINTEGRATION_RAY_ANIMATION_FRAMES 19
#define DISINTEGRATION_RAY_ANIMATION_TILES 11
#define PETRIFICATION_RAY_ANIMATION_FRAMES 20
#define PETRIFICATION_RAY_ANIMATION_TILES 12
#define DEATH_RAY_ANIMATION_FRAMES 18
#define DEATH_RAY_ANIMATION_TILES 12
#define FROST_BREATH_ANIMATION_FRAMES 5
#define FROST_BREATH_ANIMATION_TILES 10
#define FIRE_BREATH_ANIMATION_FRAMES 10
#define FIRE_BREATH_ANIMATION_TILES 10
#define DIGGING_RAY_ANIMATION_FRAMES 13
#define DIGGING_RAY_ANIMATION_TILES 9
#define GENERIC_SPELL_EFFECT_ANIMATION_FRAMES 3
#define GENERIC_SPELL_EFFECT_ANIMATION_TILES 2
#define TELEPORT_IN_ANIMATION_FRAMES 7
#define TELEPORT_IN_ANIMATION_TILES 7
#define TELEPORT_OUT_ANIMATION_FRAMES 7
#define TELEPORT_OUT_ANIMATION_TILES 7
#define LEVEL_TELEPORT_IN_ANIMATION_FRAMES 9
#define LEVEL_TELEPORT_IN_ANIMATION_TILES 9
#define LEVEL_TELEPORT_OUT_ANIMATION_FRAMES 9
#define LEVEL_TELEPORT_OUT_ANIMATION_TILES 9
#define SUMMON_DEMON_ANIMATION_FRAMES 20
#define SUMMON_DEMON_ANIMATION_TILES 20
#define SUMMON_CELESTIAL_ANIMATION_FRAMES 23
#define SUMMON_CELESTIAL_ANIMATION_TILES 23
#define SLEEP_GAS_TRAP_EFFECT_ANIMATION_FRAMES 12
#define SLEEP_GAS_TRAP_EFFECT_ANIMATION_TILES 12
#define RUST_TRAP_EFFECT_ANIMATION_FRAMES 21
#define RUST_TRAP_EFFECT_ANIMATION_TILES 21
#define FIRE_TRAP_EFFECT_ANIMATION_FRAMES 23
#define FIRE_TRAP_EFFECT_ANIMATION_TILES 23
#define POISON_CLOUD_ANIMATION_FRAMES 12
#define POISON_CLOUD_ANIMATION_TILES 12
#define PUFF_OF_SMOKE_ANIMATION_FRAMES 8
#define PUFF_OF_SMOKE_ANIMATION_TILES 8
#define MAGIC_TRAP_LIGHT_FLASH_ANIMATION_FRAMES 10
#define MAGIC_TRAP_LIGHT_FLASH_ANIMATION_TILES 10
#define MAGIC_TRAP_EFFECT_ANIMATION_FRAMES 11
#define MAGIC_TRAP_EFFECT_ANIMATION_TILES 11
#define ANTIMAGIC_TRAP_EFFECT_ANIMATION_FRAMES 10
#define ANTIMAGIC_TRAP_EFFECT_ANIMATION_TILES 10
#define POLYMORPH_TRAP_EFFECT_ANIMATION_FRAMES 10
#define POLYMORPH_TRAP_EFFECT_ANIMATION_TILES 10
#define FALLING_ROCK_TRAP_TRAP_DOOR_ANIMATION_FRAMES 13
#define FALLING_ROCK_TRAP_TRAP_DOOR_ANIMATION_TILES 13
#define FALLING_ROCK_TRAP_FALLING_ROCK_ANIMATION_FRAMES 9
#define FALLING_ROCK_TRAP_FALLING_ROCK_ANIMATION_TILES 9
#define LAND_MINE_EXPLOSION_ANIMATION_FRAMES 30
#define LAND_MINE_EXPLOSION_ANIMATION_TILES 14
#define BEAR_TRAP_CLOSE_ANIMATION_FRAMES 10
#define BEAR_TRAP_CLOSE_ANIMATION_TILES 10
#define BEAR_TRAP_OPEN_ANIMATION_FRAMES 8
#define SMALL_FIERY_EXPLOSION_ANIMATION_FRAMES 10
#define SMALL_FIERY_EXPLOSION_ANIMATION_TILES 10
#define TWISTED_CANDLE_ANIMATION_FRAMES 5
#define TWISTED_CANDLE_ANIMATION_TILES 5
#define OLD_FASHIONED_CANDLE_ANIMATION_FRAMES 5
#define OLD_FASHIONED_CANDLE_ANIMATION_TILES 5
#define ORIENTAL_BRASS_LAMP_ANIMATION_FRAMES 1
#define ORIENTAL_BRASS_LAMP_ANIMATION_TILES 1
#define ANTIQUATED_BRASS_LAMP_ANIMATION_FRAMES 1
#define ANTIQUATED_BRASS_LAMP_ANIMATION_TILES 1
#define VIBRATING_SQUARE_ANIMATION_FRAMES 1
#define VIBRATING_SQUARE_ANIMATION_TILES 1
#define CANDELABRUM_LIT_ANIMATION_FRAMES 1
#define CANDELABRUM_LIT_ANIMATION_TILES 1
#define YELLOW_LIGHT_FLASH_ANIMATION_FRAMES 7
#define YELLOW_LIGHT_FLASH_ANIMATION_TILES 7
#define BLACK_LIGHT_FLASH_ANIMATION_FRAMES 7
#define BLACK_LIGHT_FLASH_ANIMATION_TILES 7
#define BRAZIER_LIT_ANIMATION_TILES 5
#define BRAZIER_LIT_ANIMATION_FRAMES 5
#define ROCK_PIERCER_DROP_ANIMATION_FRAMES 11
#define ROCK_PIERCER_DROP_ANIMATION_TILES 11

extern NEARDATA struct animation_definition animations[];


/* Enlargement sets */
#define NUM_POSITIONS_IN_ENLARGEMENT 5

struct enlargement_definition {
    const char* enlargement_name;
    char number_of_animation_tiles;
    char number_of_animation_frames;
    char number_of_enlargement_tiles;
    char width_in_tiles;
    char height_in_tiles;
    char main_tile_x_coordinate; /* Always 0 or 1 on the last row */
    char position2tile[NUM_POSITIONS_IN_ENLARGEMENT];
    /* Enlargement position is index in the array: number from 0 to 4, X = -1 indicates main tile
            0 1 2
            3 X 4
       Value of -1 indicates the tile does not exíst, a nonnegative value indicates tile number used for the position
    */
    unsigned char position_flags[NUM_POSITIONS_IN_ENLARGEMENT];
    enum autodraw_types position_autodraw[NUM_POSITIONS_IN_ENLARGEMENT];
};

#define ENLFLAGS_DOES_NOT_CAUSE_MONSTER_SHADOW      0x01


enum enlargement_types
{
    NO_ENLARGEMENT = 0,
    DRACOLICH_ENLARGEMENT,
    DRACOLICH_STATUE_ENLARGEMENT,
    BALROG_ENLARGEMENT,
    BALROG_STATUE_ENLARGEMENT,
    BALROG_PASSIVE_DEFENSE_ENLARGEMENT,
    TARRASQUE_ENLARGEMENT,
    TARRASQUE_STATUE_ENLARGEMENT,
    MARILITH_ENLARGEMENT,
    MARILITH_STATUE_ENLARGEMENT,
    ANGEL_MALE_ENLARGEMENT,
    ANGEL_MALE_STATUE_ENLARGEMENT,
    ANGEL_FEMALE_ENLARGEMENT,
    ANGEL_FEMALE_STATUE_ENLARGEMENT,
    ARCHON_MALE_ENLARGEMENT,
    ARCHON_MALE_STATUE_ENLARGEMENT,
    ARCHON_FEMALE_ENLARGEMENT,
    ARCHON_FEMALE_STATUE_ENLARGEMENT,
    TENTACLED_ONE_ENLARGEMENT,
    TENTACLED_ONE_STATUE_ENLARGEMENT,
    ELDER_TENTACLED_ONE_ENLARGEMENT,
    ELDER_TENTACLED_ONE_STATUE_ENLARGEMENT,
    DEATH_FLAYER_ENLARGEMENT,
    DEATH_FLAYER_STATUE_ENLARGEMENT,
    GRAY_DRAGON_ENLARGEMENT,
    SILVER_DRAGON_ENLARGEMENT,
    RED_DRAGON_ENLARGEMENT,
    WHITE_DRAGON_ENLARGEMENT,
    ORANGE_DRAGON_ENLARGEMENT,
    BLACK_DRAGON_ENLARGEMENT,
    BLUE_DRAGON_ENLARGEMENT,
    GREEN_DRAGON_ENLARGEMENT,
    YELLOW_DRAGON_ENLARGEMENT,
    ANCIENT_GRAY_DRAGON_ENLARGEMENT,
    ANCIENT_SILVER_DRAGON_ENLARGEMENT,
    ANCIENT_RED_DRAGON_ENLARGEMENT,
    ANCIENT_WHITE_DRAGON_ENLARGEMENT,
    ANCIENT_ORANGE_DRAGON_ENLARGEMENT,
    ANCIENT_BLACK_DRAGON_ENLARGEMENT,
    ANCIENT_BLUE_DRAGON_ENLARGEMENT,
    ANCIENT_GREEN_DRAGON_ENLARGEMENT,
    ANCIENT_YELLOW_DRAGON_ENLARGEMENT,
    RED_DRAGON_SPECIAL_ATTACK_ENLARGEMENT,
    GRAY_DRAGON_STATUE_ENLARGEMENT,
    SILVER_DRAGON_STATUE_ENLARGEMENT,
    RED_DRAGON_STATUE_ENLARGEMENT,
    WHITE_DRAGON_STATUE_ENLARGEMENT,
    ORANGE_DRAGON_STATUE_ENLARGEMENT,
    BLACK_DRAGON_STATUE_ENLARGEMENT,
    BLUE_DRAGON_STATUE_ENLARGEMENT,
    GREEN_DRAGON_STATUE_ENLARGEMENT,
    YELLOW_DRAGON_STATUE_ENLARGEMENT,
    ANCIENT_GRAY_DRAGON_STATUE_ENLARGEMENT,
    ANCIENT_SILVER_DRAGON_STATUE_ENLARGEMENT,
    ANCIENT_RED_DRAGON_STATUE_ENLARGEMENT,
    ANCIENT_WHITE_DRAGON_STATUE_ENLARGEMENT,
    ANCIENT_ORANGE_DRAGON_STATUE_ENLARGEMENT,
    ANCIENT_BLACK_DRAGON_STATUE_ENLARGEMENT,
    ANCIENT_BLUE_DRAGON_STATUE_ENLARGEMENT,
    ANCIENT_GREEN_DRAGON_STATUE_ENLARGEMENT,
    ANCIENT_YELLOW_DRAGON_STATUE_ENLARGEMENT,
    TREE_ENLARGEMENT,
    SPRUCE_TREE_ENLARGEMENT,
    FIR_TREE_ENLARGEMENT,
    DATE_TREE_ENLARGEMENT,
    DUNGEON_NORMAL_UPSTAIRS_ENLARGEMENT,
    DUNGEON_NORMAL_BRANCH_UPSTAIRS_ENLARGEMENT,
    DUNGEON_NORMAL_SPECIAL_BRANCH_UPSTAIRS_ENLARGEMENT,
    GNOMISH_MINES_UPSTAIRS_ENLARGEMENT,
    GNOMISH_MINES_BRANCH_UPSTAIRS_ENLARGEMENT,
    GNOMISH_MINES_SPECIAL_BRANCH_UPSTAIRS_ENLARGEMENT,
    HUMAN_KNIGHT_FEMALE_ATTACK_ENLARGEMENT,
    HUMAN_KNIGHT_FEMALE_KICK_ENLARGEMENT,
    HUMAN_KNIGHT_FEMALE_CAST_ENLARGEMENT,
    HUMAN_KNIGHT_MALE_ATTACK_ENLARGEMENT,
    HUMAN_KNIGHT_MALE_KICK_ENLARGEMENT,
    HUMAN_PRIEST_MALE_LAWFUL_ATTACK_ENLARGEMENT,
    HUMAN_PRIEST_MALE_LAWFUL_KICK_ENLARGEMENT,
    HUMAN_PRIEST_MALE_LAWFUL_CAST_INDIR_ENLARGEMENT,
    HUMAN_PRIEST_MALE_LAWFUL_CAST_DIR_ENLARGEMENT,
    HUMAN_PRIEST_FEMALE_LAWFUL_ATTACK_ENLARGEMENT,
    HUMAN_PRIEST_FEMALE_LAWFUL_KICK_ENLARGEMENT,
    HUMAN_PRIEST_FEMALE_LAWFUL_CAST_INDIR_ENLARGEMENT,
    HUMAN_PRIEST_FEMALE_LAWFUL_CAST_DIR_ENLARGEMENT,
    HUMAN_PRIEST_MALE_NEUTRAL_ATTACK_ENLARGEMENT,
    HUMAN_PRIEST_MALE_NEUTRAL_KICK_ENLARGEMENT,
    HUMAN_PRIEST_MALE_NEUTRAL_CAST_INDIR_ENLARGEMENT,
    HUMAN_PRIEST_MALE_NEUTRAL_CAST_DIR_ENLARGEMENT,
    HUMAN_PRIEST_FEMALE_NEUTRAL_ATTACK_ENLARGEMENT,
    HUMAN_PRIEST_FEMALE_NEUTRAL_KICK_ENLARGEMENT,
    HUMAN_PRIEST_FEMALE_NEUTRAL_CAST_INDIR_ENLARGEMENT,
    HUMAN_PRIEST_FEMALE_NEUTRAL_CAST_DIR_ENLARGEMENT,
    HUMAN_PRIEST_MALE_CHAOTIC_ATTACK_ENLARGEMENT,
    HUMAN_PRIEST_MALE_CHAOTIC_KICK_ENLARGEMENT,
    HUMAN_PRIEST_MALE_CHAOTIC_CAST_INDIR_ENLARGEMENT,
    HUMAN_PRIEST_MALE_CHAOTIC_CAST_DIR_ENLARGEMENT,
    HUMAN_PRIEST_FEMALE_CHAOTIC_ATTACK_ENLARGEMENT,
    HUMAN_PRIEST_FEMALE_CHAOTIC_KICK_ENLARGEMENT,
    HUMAN_PRIEST_FEMALE_CHAOTIC_CAST_INDIR_ENLARGEMENT,
    HUMAN_PRIEST_FEMALE_CHAOTIC_CAST_DIR_ENLARGEMENT,
    GNOLL_PRIEST_MALE_LAWFUL_ATTACK_ENLARGEMENT,
    GNOLL_PRIEST_MALE_LAWFUL_KICK_ENLARGEMENT,
    GNOLL_PRIEST_MALE_LAWFUL_CAST_INDIR_ENLARGEMENT,
    GNOLL_PRIEST_MALE_LAWFUL_CAST_DIR_ENLARGEMENT,
    GNOLL_PRIEST_FEMALE_LAWFUL_ATTACK_ENLARGEMENT,
    GNOLL_PRIEST_FEMALE_LAWFUL_KICK_ENLARGEMENT,
    GNOLL_PRIEST_FEMALE_LAWFUL_CAST_INDIR_ENLARGEMENT,
    GNOLL_PRIEST_FEMALE_LAWFUL_CAST_DIR_ENLARGEMENT,
    GNOLL_PRIEST_MALE_NEUTRAL_ATTACK_ENLARGEMENT,
    GNOLL_PRIEST_MALE_NEUTRAL_KICK_ENLARGEMENT,
    GNOLL_PRIEST_MALE_NEUTRAL_CAST_INDIR_ENLARGEMENT,
    GNOLL_PRIEST_MALE_NEUTRAL_CAST_DIR_ENLARGEMENT,
    GNOLL_PRIEST_FEMALE_NEUTRAL_ATTACK_ENLARGEMENT,
    GNOLL_PRIEST_FEMALE_NEUTRAL_KICK_ENLARGEMENT,
    GNOLL_PRIEST_FEMALE_NEUTRAL_CAST_INDIR_ENLARGEMENT,
    GNOLL_PRIEST_FEMALE_NEUTRAL_CAST_DIR_ENLARGEMENT,
    GNOLL_PRIEST_MALE_CHAOTIC_ATTACK_ENLARGEMENT,
    GNOLL_PRIEST_MALE_CHAOTIC_KICK_ENLARGEMENT,
    GNOLL_PRIEST_MALE_CHAOTIC_CAST_INDIR_ENLARGEMENT,
    GNOLL_PRIEST_MALE_CHAOTIC_CAST_DIR_ENLARGEMENT,
    GNOLL_PRIEST_FEMALE_CHAOTIC_ATTACK_ENLARGEMENT,
    GNOLL_PRIEST_FEMALE_CHAOTIC_KICK_ENLARGEMENT,
    GNOLL_PRIEST_FEMALE_CHAOTIC_CAST_INDIR_ENLARGEMENT,
    GNOLL_PRIEST_FEMALE_CHAOTIC_CAST_DIR_ENLARGEMENT,
    ELF_PRIEST_MALE_LAWFUL_ATTACK_ENLARGEMENT,
    ELF_PRIEST_MALE_LAWFUL_KICK_ENLARGEMENT,
    ELF_PRIEST_MALE_LAWFUL_CAST_INDIR_ENLARGEMENT,
    ELF_PRIEST_MALE_LAWFUL_CAST_DIR_ENLARGEMENT,
    ELF_PRIEST_FEMALE_LAWFUL_ATTACK_ENLARGEMENT,
    ELF_PRIEST_FEMALE_LAWFUL_KICK_ENLARGEMENT,
    ELF_PRIEST_FEMALE_LAWFUL_CAST_INDIR_ENLARGEMENT,
    ELF_PRIEST_FEMALE_LAWFUL_CAST_DIR_ENLARGEMENT,
    ELF_PRIEST_MALE_NEUTRAL_ATTACK_ENLARGEMENT,
    ELF_PRIEST_MALE_NEUTRAL_KICK_ENLARGEMENT,
    ELF_PRIEST_MALE_NEUTRAL_CAST_INDIR_ENLARGEMENT,
    ELF_PRIEST_MALE_NEUTRAL_CAST_DIR_ENLARGEMENT,
    ELF_PRIEST_FEMALE_NEUTRAL_ATTACK_ENLARGEMENT,
    ELF_PRIEST_FEMALE_NEUTRAL_KICK_ENLARGEMENT,
    ELF_PRIEST_FEMALE_NEUTRAL_CAST_INDIR_ENLARGEMENT,
    ELF_PRIEST_FEMALE_NEUTRAL_CAST_DIR_ENLARGEMENT,
    ELF_PRIEST_MALE_CHAOTIC_ATTACK_ENLARGEMENT,
    ELF_PRIEST_MALE_CHAOTIC_KICK_ENLARGEMENT,
    ELF_PRIEST_MALE_CHAOTIC_CAST_INDIR_ENLARGEMENT,
    ELF_PRIEST_MALE_CHAOTIC_CAST_DIR_ENLARGEMENT,
    ELF_PRIEST_FEMALE_CHAOTIC_ATTACK_ENLARGEMENT,
    ELF_PRIEST_FEMALE_CHAOTIC_KICK_ENLARGEMENT,
    ELF_PRIEST_FEMALE_CHAOTIC_CAST_INDIR_ENLARGEMENT,
    ELF_PRIEST_FEMALE_CHAOTIC_CAST_DIR_ENLARGEMENT,
    DWARF_KNIGHT_FEMALE_ATTACK_ENLARGEMENT,
    DWARF_KNIGHT_FEMALE_KICK_ENLARGEMENT,
    DWARF_KNIGHT_MALE_ATTACK_ENLARGEMENT,
    DWARF_KNIGHT_MALE_KICK_ENLARGEMENT,
    ORC_BARBARIAN_MALE_ATTACK_ENLARGEMENT,
    ORC_BARBARIAN_MALE_KICK_ENLARGEMENT,
    ORC_BARBARIAN_FEMALE_ATTACK_ENLARGEMENT,
    ORC_BARBARIAN_FEMALE_KICK_ENLARGEMENT,
    ORC_ROGUE_FEMALE_ATTACK_ENLARGEMENT,
    ORC_ROGUE_FEMALE_KICK_ENLARGEMENT,
    ORC_ROGUE_MALE_ATTACK_ENLARGEMENT,
    ORC_ROGUE_MALE_KICK_ENLARGEMENT,
    HUMAN_ROGUE_FEMALE_ATTACK_ENLARGEMENT,
    HUMAN_ROGUE_FEMALE_KICK_ENLARGEMENT,
    HUMAN_ROGUE_MALE_ATTACK_ENLARGEMENT,
    HUMAN_ROGUE_MALE_KICK_ENLARGEMENT,
    GNOLL_ROGUE_FEMALE_ATTACK_ENLARGEMENT,
    GNOLL_ROGUE_FEMALE_KICK_ENLARGEMENT,
    GNOLL_ROGUE_MALE_ATTACK_ENLARGEMENT,
    GNOLL_ROGUE_MALE_KICK_ENLARGEMENT,
    HUMAN_TOURIST_MALE_ATTACK_ENLARGEMENT,
    HUMAN_TOURIST_MALE_KICK_ENLARGEMENT,
    HUMAN_TOURIST_FEMALE_ATTACK_ENLARGEMENT,
    HUMAN_TOURIST_FEMALE_KICK_ENLARGEMENT,
    HUMAN_BARBARIAN_MALE_ATTACK_ENLARGEMENT,
    HUMAN_BARBARIAN_MALE_KICK_ENLARGEMENT,
    HUMAN_BARBARIAN_FEMALE_ATTACK_ENLARGEMENT,
    HUMAN_BARBARIAN_FEMALE_KICK_ENLARGEMENT,
    GNOLL_BARBARIAN_MALE_ATTACK_ENLARGEMENT,
    GNOLL_BARBARIAN_MALE_KICK_ENLARGEMENT,
    GNOLL_BARBARIAN_FEMALE_ATTACK_ENLARGEMENT,
    GNOLL_BARBARIAN_FEMALE_KICK_ENLARGEMENT,
    HUMAN_VALKYRIE_FEMALE_ATTACK_ENLARGEMENT,
    HUMAN_VALKYRIE_FEMALE_KICK_ENLARGEMENT,
    DWARF_VALKYRIE_FEMALE_ATTACK_ENLARGEMENT,
    DWARF_VALKYRIE_FEMALE_KICK_ENLARGEMENT,
    ELF_RANGER_MALE_FIRE_ENLARGEMENT,
    ELF_RANGER_MALE_KICK_ENLARGEMENT,
    ELF_RANGER_FEMALE_FIRE_ENLARGEMENT,
    ELF_RANGER_FEMALE_KICK_ENLARGEMENT,
    HUMAN_RANGER_MALE_FIRE_ENLARGEMENT,
    HUMAN_RANGER_MALE_KICK_ENLARGEMENT,
    HUMAN_RANGER_FEMALE_FIRE_ENLARGEMENT,
    HUMAN_RANGER_FEMALE_KICK_ENLARGEMENT,
    ORC_RANGER_MALE_FIRE_ENLARGEMENT,
    ORC_RANGER_MALE_KICK_ENLARGEMENT,
    ORC_RANGER_FEMALE_FIRE_ENLARGEMENT,
    ORC_RANGER_FEMALE_KICK_ENLARGEMENT,
    GNOLL_RANGER_MALE_FIRE_ENLARGEMENT,
    GNOLL_RANGER_MALE_KICK_ENLARGEMENT,
    GNOLL_RANGER_FEMALE_FIRE_ENLARGEMENT,
    GNOLL_RANGER_FEMALE_KICK_ENLARGEMENT,
    GNOLL_HEALER_MALE_ATTACK_ENLARGEMENT,
    GNOLL_HEALER_MALE_KICK_ENLARGEMENT,
    GNOLL_HEALER_MALE_CAST_INDIR_ENLARGEMENT,
    GNOLL_HEALER_MALE_CAST_DIR_ENLARGEMENT,
    GNOLL_HEALER_FEMALE_ATTACK_ENLARGEMENT,
    GNOLL_HEALER_FEMALE_KICK_ENLARGEMENT,
    GNOLL_HEALER_FEMALE_CAST_INDIR_ENLARGEMENT,
    GNOLL_HEALER_FEMALE_CAST_DIR_ENLARGEMENT,
    HUMAN_HEALER_FEMALE_ATTACK_ENLARGEMENT,
    HUMAN_HEALER_FEMALE_KICK_ENLARGEMENT,
    HUMAN_HEALER_FEMALE_CAST_DIR_ENLARGEMENT,
    HUMAN_HEALER_FEMALE_CAST_INDIR_ENLARGEMENT,
    HUMAN_HEALER_MALE_ATTACK_ENLARGEMENT,
    HUMAN_HEALER_MALE_KICK_ENLARGEMENT,
    HUMAN_HEALER_MALE_CAST_DIR_ENLARGEMENT,
    HUMAN_HEALER_MALE_CAST_INDIR_ENLARGEMENT,
    HUMAN_MONK_MALE_ATTACK_ENLARGEMENT,
    HUMAN_MONK_MALE_KICK_ENLARGEMENT,
    HUMAN_MONK_MALE_CAST_INDIR_ENLARGEMENT,
    HUMAN_MONK_MALE_CAST_DIR_ENLARGEMENT,
    HUMAN_MONK_FEMALE_ATTACK_ENLARGEMENT,
    HUMAN_MONK_FEMALE_KICK_ENLARGEMENT,
    HUMAN_MONK_FEMALE_CAST_INDIR_ENLARGEMENT,
    HUMAN_MONK_FEMALE_CAST_DIR_ENLARGEMENT,
    HUMAN_SAMURAI_MALE_ATTACK_ENLARGEMENT,
    HUMAN_SAMURAI_MALE_KICK_ENLARGEMENT,
    HUMAN_SAMURAI_FEMALE_ATTACK_ENLARGEMENT,
    HUMAN_SAMURAI_FEMALE_KICK_ENLARGEMENT,
    HUMAN_WIZARD_MALE_ATTACK_ENLARGEMENT,
    HUMAN_WIZARD_MALE_KICK_ENLARGEMENT,
    HUMAN_WIZARD_MALE_CAST_INDIR_ENLARGEMENT,
    HUMAN_WIZARD_MALE_CAST_DIR_ENLARGEMENT,
    HUMAN_WIZARD_FEMALE_ATTACK_ENLARGEMENT,
    HUMAN_WIZARD_FEMALE_KICK_ENLARGEMENT,
    HUMAN_WIZARD_FEMALE_CAST_INDIR_ENLARGEMENT,
    HUMAN_WIZARD_FEMALE_CAST_DIR_ENLARGEMENT,
    ELF_WIZARD_MALE_ATTACK_ENLARGEMENT,
    ELF_WIZARD_MALE_KICK_ENLARGEMENT,
    ELF_WIZARD_MALE_CAST_INDIR_ENLARGEMENT,
    ELF_WIZARD_MALE_CAST_DIR_ENLARGEMENT,
    ELF_WIZARD_FEMALE_ATTACK_ENLARGEMENT,
    ELF_WIZARD_FEMALE_KICK_ENLARGEMENT,
    ELF_WIZARD_FEMALE_CAST_INDIR_ENLARGEMENT,
    ELF_WIZARD_FEMALE_CAST_DIR_ENLARGEMENT,
    ORC_WIZARD_MALE_ATTACK_ENLARGEMENT,
    ORC_WIZARD_MALE_KICK_ENLARGEMENT,
    ORC_WIZARD_MALE_CAST_INDIR_ENLARGEMENT,
    ORC_WIZARD_MALE_CAST_DIR_ENLARGEMENT,
    ORC_WIZARD_FEMALE_ATTACK_ENLARGEMENT,
    ORC_WIZARD_FEMALE_KICK_ENLARGEMENT,
    ORC_WIZARD_FEMALE_CAST_INDIR_ENLARGEMENT,
    ORC_WIZARD_FEMALE_CAST_DIR_ENLARGEMENT,
    DWARF_CAVEMAN_MALE_ATTACK_ENLARGEMENT,
    DWARF_CAVEMAN_MALE_KICK_ENLARGEMENT,
    DWARF_CAVEMAN_FEMALE_ATTACK_ENLARGEMENT,
    DWARF_CAVEMAN_FEMALE_KICK_ENLARGEMENT,
    HUMAN_CAVEMAN_MALE_ATTACK_ENLARGEMENT,
    HUMAN_CAVEMAN_MALE_KICK_ENLARGEMENT,
    HUMAN_CAVEMAN_FEMALE_ATTACK_ENLARGEMENT,
    HUMAN_CAVEMAN_FEMALE_KICK_ENLARGEMENT,
    GNOLL_CAVEMAN_MALE_ATTACK_ENLARGEMENT,
    GNOLL_CAVEMAN_MALE_KICK_ENLARGEMENT,
    GNOLL_CAVEMAN_FEMALE_ATTACK_ENLARGEMENT,
    GNOLL_CAVEMAN_FEMALE_KICK_ENLARGEMENT,
    DWARF_ARCHAEOLOGIST_MALE_ATTACK_ENLARGEMENT,
    DWARF_ARCHAEOLOGIST_MALE_KICK_ENLARGEMENT,
    DWARF_ARCHAEOLOGIST_FEMALE_ATTACK_ENLARGEMENT,
    DWARF_ARCHAEOLOGIST_FEMALE_KICK_ENLARGEMENT,
    HUMAN_ARCHAEOLOGIST_MALE_ATTACK_ENLARGEMENT,
    HUMAN_ARCHAEOLOGIST_MALE_KICK_ENLARGEMENT,
    HUMAN_ARCHAEOLOGIST_FEMALE_ATTACK_ENLARGEMENT,
    HUMAN_ARCHAEOLOGIST_FEMALE_KICK_ENLARGEMENT,
    PONY_ENLARGEMENT,
    PONY_STATUE_ENLARGEMENT,
    HORSE_ENLARGEMENT,
    HORSE_STATUE_ENLARGEMENT,
    WARHORSE_ENLARGEMENT,
    WARHORSE_STATUE_ENLARGEMENT,
    PEGASUS_ENLARGEMENT,
    PEGASUS_STATUE_ENLARGEMENT,
    WHITE_UNICORN_ENLARGEMENT,
    WHITE_UNICORN_STATUE_ENLARGEMENT,
    GRAY_UNICORN_ENLARGEMENT,
    GRAY_UNICORN_STATUE_ENLARGEMENT,
    BLACK_UNICORN_ENLARGEMENT,
    BLACK_UNICORN_STATUE_ENLARGEMENT,
    RAM_ENLARGEMENT,
    RAM_STATUE_ENLARGEMENT,
    LARGE_RAM_ENLARGEMENT,
    LARGE_RAM_STATUE_ENLARGEMENT,
    WARRAM_ENLARGEMENT,
    WARRAM_STATUE_ENLARGEMENT,
    PLAINS_CENTAUR_MALE_ENLARGEMENT,
    PLAINS_CENTAUR_MALE_STATUE_ENLARGEMENT,
    PLAINS_CENTAUR_FEMALE_ENLARGEMENT,
    PLAINS_CENTAUR_FEMALE_STATUE_ENLARGEMENT,
    FOREST_CENTAUR_MALE_ENLARGEMENT,
    FOREST_CENTAUR_MALE_STATUE_ENLARGEMENT,
    FOREST_CENTAUR_FEMALE_ENLARGEMENT,
    FOREST_CENTAUR_FEMALE_STATUE_ENLARGEMENT,
    MOUNTAIN_CENTAUR_MALE_ENLARGEMENT,
    MOUNTAIN_CENTAUR_MALE_STATUE_ENLARGEMENT,
    MOUNTAIN_CENTAUR_FEMALE_ENLARGEMENT,
    MOUNTAIN_CENTAUR_FEMALE_STATUE_ENLARGEMENT,
    LARGE_DOG_ENLARGEMENT,
    LARGE_DOG_STATUE_ENLARGEMENT,
    DIREWOLF_ENLARGEMENT,
    DIREWOLF_STATUE_ENLARGEMENT,
    LARGE_DIREWOLF_ENLARGEMENT,
    LARGE_DIREWOLF_STATUE_ENLARGEMENT,
    DUNGEON_NORMAL_SMALLER_UPSTAIRS_ENLARGEMENT,
    DUNGEON_UNDEAD_UPSTAIRS_ENLARGEMENT,
    DUNGEON_UNDEAD_BRANCH_UPSTAIRS_ENLARGEMENT,
    DUNGEON_UNDEAD_SPECIAL_BRANCH_UPSTAIRS_ENLARGEMENT,
    DRACOLICH_ATTACK_ENLARGEMENT,
    SUMMON_DEMON_ENLARGEMENT,
    SUMMON_CELESTIAL_ENLARGEMENT,
    MAGIC_TRAP_LIGHT_FLASH_ENLARGEMENT,
    FALLING_ROCK_TRAP_TRAP_DOOR_ENLARGEMENT,
    FALLING_ROCK_TRAP_FALLING_ROCK_ENLARGEMENT,
    BOOKSHELF_ENLARGEMENT,
    WEAPON_RACK_ENLARGEMENT,
    ROCK_PIERCER_DROPPING_ENLARGEMENT,
    IRON_PIERCER_DROPPING_ENLARGEMENT,
    GLASS_PIERCER_DROPPING_ENLARGEMENT,
    YELLOW_LIGHT_FLASH_ENLARGEMENT,
    BLACK_LIGHT_FLASH_ENLARGEMENT,
    OGRE_MALE_ENLARGEMENT,
    OGRE_MALE_STATUE_ENLARGEMENT,
    OGRE_FEMALE_ENLARGEMENT,
    OGRE_FEMALE_STATUE_ENLARGEMENT,
    OGRE_LORD_MALE_ENLARGEMENT,
    OGRE_LORD_MALE_STATUE_ENLARGEMENT,
    OGRE_LORD_FEMALE_ENLARGEMENT,
    OGRE_LORD_FEMALE_STATUE_ENLARGEMENT,
    OGRE_OVERLORD_MALE_ENLARGEMENT,
    OGRE_OVERLORD_MALE_STATUE_ENLARGEMENT,
    OGRE_OVERLORD_FEMALE_ENLARGEMENT,
    OGRE_OVERLORD_FEMALE_STATUE_ENLARGEMENT,
    OGRE_KING_MALE_ENLARGEMENT,
    OGRE_KING_MALE_STATUE_ENLARGEMENT,
    OGRE_KING_FEMALE_ENLARGEMENT,
    OGRE_KING_FEMALE_STATUE_ENLARGEMENT,
    OGRE_MAGE_MALE_ENLARGEMENT,
    OGRE_MAGE_MALE_STATUE_ENLARGEMENT,
    OGRE_MAGE_FEMALE_ENLARGEMENT,
    OGRE_MAGE_FEMALE_STATUE_ENLARGEMENT,
    OGRE_ARCHMAGE_MALE_ENLARGEMENT,
    OGRE_ARCHMAGE_MALE_STATUE_ENLARGEMENT,
    OGRE_ARCHMAGE_FEMALE_ENLARGEMENT,
    OGRE_ARCHMAGE_FEMALE_STATUE_ENLARGEMENT,
    GREATER_MUMMY_ENLARGEMENT,
    GREATER_MUMMY_STATUE_ENLARGEMENT,
    GREATER_MUMMY_PRIEST_ENLARGEMENT,
    GREATER_MUMMY_PRIEST_STATUE_ENLARGEMENT,
    GREATER_MUMMY_HIGH_PRIEST_ENLARGEMENT,
    GREATER_MUMMY_HIGH_PRIEST_STATUE_ENLARGEMENT,
    GREATER_MUMMY_PHARAOH_ENLARGEMENT,
    GREATER_MUMMY_PHARAOH_STATUE_ENLARGEMENT,
    ROCK_PIERCER_DROP_ENLARGEMENT,
    MAX_ENLARGEMENTS
};

#define DRACOLICH_ENLARGEMENT_TILES 5
#define DRACOLICH_STATUE_ENLARGEMENT_TILES 5
#define BALROG_ENLARGEMENT_TILES 5
#define BALROG_STATUE_ENLARGEMENT_TILES 5
#define BALROG_PASSIVE_DEFENSE_ENLARGEMENT_TILES 5
#define TARRASQUE_ENLARGEMENT_TILES 5
#define TARRASQUE_STATUE_ENLARGEMENT_TILES 5
#define MARILITH_ENLARGEMENT_TILES 5
#define MARILITH_STATUE_ENLARGEMENT_TILES 5
#define ANGEL_MALE_ENLARGEMENT_TILES 5
#define ANGEL_MALE_STATUE_ENLARGEMENT_TILES 5
#define ANGEL_FEMALE_ENLARGEMENT_TILES 5
#define ANGEL_FEMALE_STATUE_ENLARGEMENT_TILES 5
#define ARCHON_MALE_ENLARGEMENT_TILES 5
#define ARCHON_MALE_STATUE_ENLARGEMENT_TILES 5
#define ARCHON_FEMALE_ENLARGEMENT_TILES 5
#define ARCHON_FEMALE_STATUE_ENLARGEMENT_TILES 5
#define TENTACLED_ONE_ENLARGEMENT_TILES 5
#define TENTACLED_ONE_STATUE_ENLARGEMENT_TILES 5
#define ELDER_TENTACLED_ONE_ENLARGEMENT_TILES 5
#define ELDER_TENTACLED_ONE_STATUE_ENLARGEMENT_TILES 5
#define DEATH_FLAYER_ENLARGEMENT_TILES 5
#define DEATH_FLAYER_STATUE_ENLARGEMENT_TILES 5
#define GRAY_DRAGON_ENLARGEMENT_TILES 5
#define SILVER_DRAGON_ENLARGEMENT_TILES 5
#define RED_DRAGON_ENLARGEMENT_TILES 5
#define WHITE_DRAGON_ENLARGEMENT_TILES 5
#define ORANGE_DRAGON_ENLARGEMENT_TILES 5
#define BLACK_DRAGON_ENLARGEMENT_TILES 5
#define BLUE_DRAGON_ENLARGEMENT_TILES 5
#define GREEN_DRAGON_ENLARGEMENT_TILES 5
#define YELLOW_DRAGON_ENLARGEMENT_TILES 5
#define ANCIENT_GRAY_DRAGON_ENLARGEMENT_TILES 5
#define ANCIENT_SILVER_DRAGON_ENLARGEMENT_TILES 5
#define ANCIENT_RED_DRAGON_ENLARGEMENT_TILES 5
#define ANCIENT_WHITE_DRAGON_ENLARGEMENT_TILES 5
#define ANCIENT_ORANGE_DRAGON_ENLARGEMENT_TILES 5
#define ANCIENT_BLACK_DRAGON_ENLARGEMENT_TILES 5
#define ANCIENT_BLUE_DRAGON_ENLARGEMENT_TILES 5
#define ANCIENT_GREEN_DRAGON_ENLARGEMENT_TILES 5
#define ANCIENT_YELLOW_DRAGON_ENLARGEMENT_TILES 5
#define RED_DRAGON_SPECIAL_ATTACK_ENLARGEMENT_TILES 5
#define GRAY_DRAGON_STATUE_ENLARGEMENT_TILES 5
#define SILVER_DRAGON_STATUE_ENLARGEMENT_TILES 5
#define RED_DRAGON_STATUE_ENLARGEMENT_TILES 5
#define WHITE_DRAGON_STATUE_ENLARGEMENT_TILES 5
#define ORANGE_DRAGON_STATUE_ENLARGEMENT_TILES 5
#define BLACK_DRAGON_STATUE_ENLARGEMENT_TILES 5
#define BLUE_DRAGON_STATUE_ENLARGEMENT_TILES 5
#define GREEN_DRAGON_STATUE_ENLARGEMENT_TILES 5
#define YELLOW_DRAGON_STATUE_ENLARGEMENT_TILES 5
#define ANCIENT_GRAY_DRAGON_STATUE_ENLARGEMENT_TILES 5
#define ANCIENT_SILVER_DRAGON_STATUE_ENLARGEMENT_TILES 5
#define ANCIENT_RED_DRAGON_STATUE_ENLARGEMENT_TILES 5
#define ANCIENT_WHITE_DRAGON_STATUE_ENLARGEMENT_TILES 5
#define ANCIENT_ORANGE_DRAGON_STATUE_ENLARGEMENT_TILES 5
#define ANCIENT_BLACK_DRAGON_STATUE_ENLARGEMENT_TILES 5
#define ANCIENT_BLUE_DRAGON_STATUE_ENLARGEMENT_TILES 5
#define ANCIENT_GREEN_DRAGON_STATUE_ENLARGEMENT_TILES 5
#define ANCIENT_YELLOW_DRAGON_STATUE_ENLARGEMENT_TILES 5
#define TREE_ENLARGEMENT_TILES 5
#define UPSTAIRS_ENLARGEMENT_TILES 1
#define BRANCH_UPSTAIRS_ENLARGEMENT_TILES 1
#define SPECIAL_BRANCH_UPSTAIRS_ENLARGEMENT_TILES 1
#define HUMAN_KNIGHT_FEMALE_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_KNIGHT_FEMALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_KNIGHT_FEMALE_CAST_ENLARGEMENT_TILES 1
#define HUMAN_KNIGHT_MALE_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_KNIGHT_MALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_PRIEST_MALE_LAWFUL_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_PRIEST_MALE_LAWFUL_KICK_ENLARGEMENT_TILES 2
#define HUMAN_PRIEST_MALE_LAWFUL_CAST_INDIR_ENLARGEMENT_TILES 5
#define HUMAN_PRIEST_MALE_LAWFUL_CAST_DIR_ENLARGEMENT_TILES 5
#define HUMAN_PRIEST_FEMALE_LAWFUL_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_PRIEST_FEMALE_LAWFUL_KICK_ENLARGEMENT_TILES 2
#define HUMAN_PRIEST_FEMALE_LAWFUL_CAST_INDIR_ENLARGEMENT_TILES 5
#define HUMAN_PRIEST_FEMALE_LAWFUL_CAST_DIR_ENLARGEMENT_TILES 5
#define HUMAN_PRIEST_MALE_NEUTRAL_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_PRIEST_MALE_NEUTRAL_KICK_ENLARGEMENT_TILES 2
#define HUMAN_PRIEST_MALE_NEUTRAL_CAST_INDIR_ENLARGEMENT_TILES 5
#define HUMAN_PRIEST_MALE_NEUTRAL_CAST_DIR_ENLARGEMENT_TILES 5
#define HUMAN_PRIEST_FEMALE_NEUTRAL_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_PRIEST_FEMALE_NEUTRAL_KICK_ENLARGEMENT_TILES 2
#define HUMAN_PRIEST_FEMALE_NEUTRAL_CAST_INDIR_ENLARGEMENT_TILES 5
#define HUMAN_PRIEST_FEMALE_NEUTRAL_CAST_DIR_ENLARGEMENT_TILES 5
#define HUMAN_PRIEST_MALE_CHAOTIC_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_PRIEST_MALE_CHAOTIC_KICK_ENLARGEMENT_TILES 2
#define HUMAN_PRIEST_MALE_CHAOTIC_CAST_INDIR_ENLARGEMENT_TILES 5
#define HUMAN_PRIEST_MALE_CHAOTIC_CAST_DIR_ENLARGEMENT_TILES 2
#define HUMAN_PRIEST_FEMALE_CHAOTIC_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_PRIEST_FEMALE_CHAOTIC_KICK_ENLARGEMENT_TILES 2
#define HUMAN_PRIEST_FEMALE_CHAOTIC_CAST_INDIR_ENLARGEMENT_TILES 5
#define HUMAN_PRIEST_FEMALE_CHAOTIC_CAST_DIR_ENLARGEMENT_TILES 2
#define GNOLL_PRIEST_MALE_LAWFUL_ATTACK_ENLARGEMENT_TILES 2
#define GNOLL_PRIEST_MALE_LAWFUL_KICK_ENLARGEMENT_TILES 2
#define GNOLL_PRIEST_FEMALE_LAWFUL_ATTACK_ENLARGEMENT_TILES 2
#define GNOLL_PRIEST_FEMALE_LAWFUL_KICK_ENLARGEMENT_TILES 2
#define GNOLL_PRIEST_MALE_NEUTRAL_ATTACK_ENLARGEMENT_TILES 2
#define GNOLL_PRIEST_MALE_NEUTRAL_KICK_ENLARGEMENT_TILES 2
#define GNOLL_PRIEST_FEMALE_NEUTRAL_ATTACK_ENLARGEMENT_TILES 2
#define GNOLL_PRIEST_FEMALE_NEUTRAL_KICK_ENLARGEMENT_TILES 2
#define GNOLL_PRIEST_MALE_CHAOTIC_ATTACK_ENLARGEMENT_TILES 2
#define GNOLL_PRIEST_MALE_CHAOTIC_KICK_ENLARGEMENT_TILES 2
#define GNOLL_PRIEST_MALE_CHAOTIC_CAST_INDIR_ENLARGEMENT_TILES 5
#define GNOLL_PRIEST_MALE_CHAOTIC_CAST_DIR_ENLARGEMENT_TILES 5
#define GNOLL_PRIEST_FEMALE_CHAOTIC_ATTACK_ENLARGEMENT_TILES 2
#define GNOLL_PRIEST_FEMALE_CHAOTIC_KICK_ENLARGEMENT_TILES 2
#define GNOLL_PRIEST_FEMALE_CHAOTIC_CAST_INDIR_ENLARGEMENT_TILES 5
#define GNOLL_PRIEST_FEMALE_CHAOTIC_CAST_DIR_ENLARGEMENT_TILES 5
#define ELF_PRIEST_MALE_LAWFUL_ATTACK_ENLARGEMENT_TILES 5
#define ELF_PRIEST_MALE_LAWFUL_KICK_ENLARGEMENT_TILES 2
#define ELF_PRIEST_FEMALE_LAWFUL_ATTACK_ENLARGEMENT_TILES 5
#define ELF_PRIEST_FEMALE_LAWFUL_KICK_ENLARGEMENT_TILES 2
#define ELF_PRIEST_MALE_NEUTRAL_ATTACK_ENLARGEMENT_TILES 5
#define ELF_PRIEST_MALE_NEUTRAL_KICK_ENLARGEMENT_TILES 2
#define ELF_PRIEST_FEMALE_NEUTRAL_ATTACK_ENLARGEMENT_TILES 5
#define ELF_PRIEST_FEMALE_NEUTRAL_KICK_ENLARGEMENT_TILES 2
#define ELF_PRIEST_MALE_CHAOTIC_ATTACK_ENLARGEMENT_TILES 5
#define ELF_PRIEST_MALE_CHAOTIC_KICK_ENLARGEMENT_TILES 2
#define ELF_PRIEST_FEMALE_CHAOTIC_ATTACK_ENLARGEMENT_TILES 5
#define ELF_PRIEST_FEMALE_CHAOTIC_KICK_ENLARGEMENT_TILES 2
#define DWARF_KNIGHT_FEMALE_ATTACK_ENLARGEMENT_TILES 2
#define DWARF_KNIGHT_FEMALE_KICK_ENLARGEMENT_TILES 2
#define DWARF_KNIGHT_MALE_ATTACK_ENLARGEMENT_TILES 2
#define DWARF_KNIGHT_MALE_KICK_ENLARGEMENT_TILES 2
#define ORC_BARBARIAN_MALE_ATTACK_ENLARGEMENT_TILES 2
#define ORC_BARBARIAN_MALE_KICK_ENLARGEMENT_TILES 2
#define ORC_BARBARIAN_FEMALE_ATTACK_ENLARGEMENT_TILES 2
#define ORC_BARBARIAN_FEMALE_KICK_ENLARGEMENT_TILES 2
#define ORC_ROGUE_FEMALE_ATTACK_ENLARGEMENT_TILES 2
#define ORC_ROGUE_FEMALE_KICK_ENLARGEMENT_TILES 2
#define ORC_ROGUE_MALE_ATTACK_ENLARGEMENT_TILES 2
#define ORC_ROGUE_MALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_ROGUE_FEMALE_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_ROGUE_FEMALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_ROGUE_MALE_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_ROGUE_MALE_KICK_ENLARGEMENT_TILES 2
#define GNOLL_ROGUE_FEMALE_ATTACK_ENLARGEMENT_TILES 2
#define GNOLL_ROGUE_FEMALE_KICK_ENLARGEMENT_TILES 2
#define GNOLL_ROGUE_MALE_ATTACK_ENLARGEMENT_TILES 2
#define GNOLL_ROGUE_MALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_TOURIST_MALE_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_TOURIST_MALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_TOURIST_FEMALE_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_TOURIST_FEMALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_BARBARIAN_MALE_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_BARBARIAN_MALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_BARBARIAN_FEMALE_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_BARBARIAN_FEMALE_KICK_ENLARGEMENT_TILES 2
#define GNOLL_BARBARIAN_MALE_ATTACK_ENLARGEMENT_TILES 2
#define GNOLL_BARBARIAN_MALE_KICK_ENLARGEMENT_TILES 2
#define GNOLL_BARBARIAN_FEMALE_ATTACK_ENLARGEMENT_TILES 2
#define GNOLL_BARBARIAN_FEMALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_VALKYRIE_FEMALE_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_VALKYRIE_FEMALE_KICK_ENLARGEMENT_TILES 2
#define DWARF_VALKYRIE_FEMALE_ATTACK_ENLARGEMENT_TILES 2
#define DWARF_VALKYRIE_FEMALE_KICK_ENLARGEMENT_TILES 2
#define ELF_RANGER_MALE_FIRE_ENLARGEMENT_TILES 2
#define ELF_RANGER_MALE_KICK_ENLARGEMENT_TILES 2
#define ELF_RANGER_FEMALE_FIRE_ENLARGEMENT_TILES 2
#define ELF_RANGER_FEMALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_RANGER_MALE_FIRE_ENLARGEMENT_TILES 2
#define HUMAN_RANGER_MALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_RANGER_FEMALE_FIRE_ENLARGEMENT_TILES 2
#define HUMAN_RANGER_FEMALE_KICK_ENLARGEMENT_TILES 2
#define ORC_RANGER_MALE_FIRE_ENLARGEMENT_TILES 2
#define ORC_RANGER_MALE_KICK_ENLARGEMENT_TILES 2
#define ORC_RANGER_FEMALE_FIRE_ENLARGEMENT_TILES 2
#define ORC_RANGER_FEMALE_KICK_ENLARGEMENT_TILES 2
#define GNOLL_RANGER_MALE_FIRE_ENLARGEMENT_TILES 2
#define GNOLL_RANGER_MALE_KICK_ENLARGEMENT_TILES 2
#define GNOLL_RANGER_FEMALE_FIRE_ENLARGEMENT_TILES 2
#define GNOLL_RANGER_FEMALE_KICK_ENLARGEMENT_TILES 2
#define GNOLL_HEALER_MALE_ATTACK_ENLARGEMENT_TILES 2
#define GNOLL_HEALER_MALE_KICK_ENLARGEMENT_TILES 2
#define GNOLL_HEALER_FEMALE_ATTACK_ENLARGEMENT_TILES 2
#define GNOLL_HEALER_FEMALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_HEALER_FEMALE_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_HEALER_FEMALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_HEALER_FEMALE_CAST_DIR_ENLARGEMENT_TILES 5
#define HUMAN_HEALER_FEMALE_CAST_INDIR_ENLARGEMENT_TILES 5
#define HUMAN_HEALER_MALE_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_HEALER_MALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_HEALER_MALE_CAST_DIR_ENLARGEMENT_TILES 5
#define HUMAN_HEALER_MALE_CAST_INDIR_ENLARGEMENT_TILES 5
#define HUMAN_MONK_MALE_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_MONK_MALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_MONK_FEMALE_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_MONK_FEMALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_SAMURAI_MALE_ATTACK_ENLARGEMENT_TILES 5
#define HUMAN_SAMURAI_MALE_KICK_ENLARGEMENT_TILES 5
#define HUMAN_SAMURAI_FEMALE_ATTACK_ENLARGEMENT_TILES 5
#define HUMAN_SAMURAI_FEMALE_KICK_ENLARGEMENT_TILES 5
#define HUMAN_WIZARD_MALE_ATTACK_ENLARGEMENT_TILES 5
#define HUMAN_WIZARD_MALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_WIZARD_MALE_CAST_INDIR_ENLARGEMENT_TILES 5
#define HUMAN_WIZARD_MALE_CAST_DIR_ENLARGEMENT_TILES 5
#define HUMAN_WIZARD_FEMALE_ATTACK_ENLARGEMENT_TILES 5
#define HUMAN_WIZARD_FEMALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_WIZARD_FEMALE_CAST_INDIR_ENLARGEMENT_TILES 5
#define HUMAN_WIZARD_FEMALE_CAST_DIR_ENLARGEMENT_TILES 5
#define ELF_WIZARD_MALE_ATTACK_ENLARGEMENT_TILES 5
#define ELF_WIZARD_MALE_KICK_ENLARGEMENT_TILES 2
#define ELF_WIZARD_MALE_CAST_INDIR_ENLARGEMENT_TILES 5
#define ELF_WIZARD_MALE_CAST_DIR_ENLARGEMENT_TILES 5
#define ELF_WIZARD_FEMALE_ATTACK_ENLARGEMENT_TILES 5
#define ELF_WIZARD_FEMALE_KICK_ENLARGEMENT_TILES 2
#define ELF_WIZARD_FEMALE_CAST_INDIR_ENLARGEMENT_TILES 5
#define ELF_WIZARD_FEMALE_CAST_DIR_ENLARGEMENT_TILES 5
#define ORC_WIZARD_MALE_ATTACK_ENLARGEMENT_TILES 2
#define ORC_WIZARD_MALE_KICK_ENLARGEMENT_TILES 2
#define ORC_WIZARD_MALE_CAST_INDIR_ENLARGEMENT_TILES 5
#define ORC_WIZARD_MALE_CAST_DIR_ENLARGEMENT_TILES 5
#define ORC_WIZARD_FEMALE_ATTACK_ENLARGEMENT_TILES 2
#define ORC_WIZARD_FEMALE_KICK_ENLARGEMENT_TILES 2
#define ORC_WIZARD_FEMALE_CAST_INDIR_ENLARGEMENT_TILES 5
#define ORC_WIZARD_FEMALE_CAST_DIR_ENLARGEMENT_TILES 5
#define DWARF_CAVEMAN_MALE_ATTACK_ENLARGEMENT_TILES 2
#define DWARF_CAVEMAN_MALE_KICK_ENLARGEMENT_TILES 2
#define DWARF_CAVEMAN_FEMALE_ATTACK_ENLARGEMENT_TILES 2
#define DWARF_CAVEMAN_FEMALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_CAVEMAN_MALE_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_CAVEMAN_MALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_CAVEMAN_FEMALE_ATTACK_ENLARGEMENT_TILES 2
#define HUMAN_CAVEMAN_FEMALE_KICK_ENLARGEMENT_TILES 2
#define GNOLL_CAVEMAN_MALE_ATTACK_ENLARGEMENT_TILES 2
#define GNOLL_CAVEMAN_MALE_KICK_ENLARGEMENT_TILES 2
#define GNOLL_CAVEMAN_FEMALE_ATTACK_ENLARGEMENT_TILES 2
#define GNOLL_CAVEMAN_FEMALE_KICK_ENLARGEMENT_TILES 2
#define DWARF_ARCHAEOLOGIST_MALE_ATTACK_ENLARGEMENT_TILES 5
#define DWARF_ARCHAEOLOGIST_MALE_KICK_ENLARGEMENT_TILES 2
#define DWARF_ARCHAEOLOGIST_FEMALE_ATTACK_ENLARGEMENT_TILES 5
#define DWARF_ARCHAEOLOGIST_FEMALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_ARCHAEOLOGIST_MALE_ATTACK_ENLARGEMENT_TILES 5
#define HUMAN_ARCHAEOLOGIST_MALE_KICK_ENLARGEMENT_TILES 2
#define HUMAN_ARCHAEOLOGIST_FEMALE_ATTACK_ENLARGEMENT_TILES 5
#define HUMAN_ARCHAEOLOGIST_FEMALE_KICK_ENLARGEMENT_TILES 2
#define PONY_ENLARGEMENT_TILES 2
#define PONY_STATUE_ENLARGEMENT_TILES 2
#define HORSE_ENLARGEMENT_TILES 2
#define HORSE_STATUE_ENLARGEMENT_TILES 2
#define WARHORSE_ENLARGEMENT_TILES 2
#define WARHORSE_STATUE_ENLARGEMENT_TILES 2
#define PEGASUS_ENLARGEMENT_TILES 1
#define PEGASUS_STATUE_ENLARGEMENT_TILES 1
#define WHITE_UNICORN_ENLARGEMENT_TILES 1
#define WHITE_UNICORN_STATUE_ENLARGEMENT_TILES 1
#define GRAY_UNICORN_ENLARGEMENT_TILES 1
#define GRAY_UNICORN_STATUE_ENLARGEMENT_TILES 1
#define BLACK_UNICORN_ENLARGEMENT_TILES 1
#define BLACK_UNICORN_STATUE_ENLARGEMENT_TILES 1
#define RAM_ENLARGEMENT_TILES 2
#define RAM_STATUE_ENLARGEMENT_TILES 2
#define LARGE_RAM_ENLARGEMENT_TILES 2
#define LARGE_RAM_STATUE_ENLARGEMENT_TILES 2
#define WARRAM_ENLARGEMENT_TILES 2
#define WARRAM_STATUE_ENLARGEMENT_TILES 2
#define CENTAUR_ENLARGEMENT_TILES 2 /* Only on suffices for now */
#define DUNGEON_NORMAL_SMALLER_UPSTAIRS_ENLARGEMENT_TILES 1
#define DUNGEON_UNDEAD_UPSTAIRS_ENLARGEMENT_TILES 1
#define DUNGEON_UNDEAD_BRANCH_UPSTAIRS_ENLARGEMENT_TILES 1
#define DUNGEON_UNDEAD_SPECIAL_BRANCH_UPSTAIRS_ENLARGEMENT_TILES 1
#define DRACOLICH_ATTACK_ENLARGEMENT_TILES 5
#define SUMMON_DEMON_ENLARGEMENT_TILES 5
#define SUMMON_CELESTIAL_ENLARGEMENT_TILES 5
#define MAGIC_TRAP_LIGHT_FLASH_ENLARGEMENT_TILES 2
#define POLYMORPH_TRAP_LIGHT_FLASH_ENLARGEMENT_TILES 2
#define FALLING_ROCK_TRAP_TRAP_DOOR_ENLARGEMENT_TILES 1
#define FALLING_ROCK_TRAP_FALLING_ROCK_ENLARGEMENT_TILES 1
#define BOOKSHELF_ENLARGEMENT_TILES 1
#define WEAPON_RACK_ENLARGEMENT_TILES 1
#define ROCK_PIERCER_DROPPING_ENLARGEMENT_TILES 1
#define IRON_PIERCER_DROPPING_ENLARGEMENT_TILES 1
#define GLASS_PIERCER_DROPPING_ENLARGEMENT_TILES 1
#define YELLOW_LIGHT_FLASH_ENLARGEMENT_TILES 2
#define BLACK_LIGHT_FLASH_ENLARGEMENT_TILES 2
#define OGRE_ENLARGEMENT_TILES 5

extern NEARDATA struct enlargement_definition enlargements[];


/* Replacements */
#define MAX_TILES_PER_REPLACEMENT 32

enum replacement_action_types
{
    REPLACEMENT_ACTION_NO_ACTION = 0,
    REPLACEMENT_ACTION_BOTTOM_TILE,
    REPLACEMENT_ACTION_SHORE_TILE,
    REPLACEMENT_ACTION_SHORE_ADJUSTED_TILE,
    REPLACEMENT_ACTION_FLOOR_ADJUSTED_TILE,
    REPLACEMENT_ACTION_SHORE_AND_FLOOR_ADJUSTED_TILE,
    REPLACEMENT_ACTION_OBJECT_LIT,
    REPLACEMENT_ACTION_LOCATION_LIT,
    REPLACEMENT_ACTION_COIN_QUANTITY,
    REPLACEMENT_ACTION_PEBBLE_QUANTITY,
    REPLACEMENT_ACTION_CHEST,
    REPLACEMENT_ACTION_LOCATION_HORIZONTAL,
    REPLACEMENT_ACTION_LEVER_STATE,
    REPLACEMENT_ACTION_AUTODRAW,
    REPLACEMENT_ACTION_AUTODRAW_AND_OBJECT_LIT,
    REPLACEMENT_ACTION_AUTODRAW_AND_OBJECT_UCHAIN,
    REPLACEMENT_ACTION_AUTODRAW_AND_LONG_WORM,
    REPLACEMENT_ACTION_PIERCER,
    REPLACEMENT_ACTION_BEAR_TRAP,
    REPLACEMENT_ACTION_COFFIN,
};


struct replacement_definition {
    const char* replacement_name;
    char number_of_tiles;
    unsigned long replacement_events;
    enum replacement_action_types replacement_action; /* hard-coded - defines which tile to use and when */
    enum autodraw_types general_autodraw; /* For zero-tile replacements */
    const char* tile_names[MAX_TILES_PER_REPLACEMENT];
    short tile_animation[MAX_TILES_PER_REPLACEMENT];
    short tile_enlargement[MAX_TILES_PER_REPLACEMENT];
    enum autodraw_types tile_autodraw[MAX_TILES_PER_REPLACEMENT];
    unsigned long tile_flags[MAX_TILES_PER_REPLACEMENT];
};

#define REPLACEMENT_EVENT_NO_EVENT              0x00000000UL
#define REPLACEMENT_EVENT_UPDATE_FROM_BELOW     0x00000001UL
#define REPLACEMENT_EVENT_UPDATE_FROM_TOP       0x00000002UL
#define REPLACEMENT_EVENT_UPDATE_FROM_LEFT      0x00000004UL
#define REPLACEMENT_EVENT_UPDATE_FROM_RIGHT     0x00000008UL

#define RTF_SKIP   0x00000001UL

enum replacement_types
{
    NO_REPLACEMENT = 0,
    DUNGEON_NORMAL_STONE_REPLACEMENT,
    DUNGEON_NORMAL_VWALL_REPLACEMENT,
    DUNGEON_NORMAL_CRWALL_REPLACEMENT,
    DUNGEON_NORMAL_TRWALL_REPLACEMENT,
    DUNGEON_NORMAL_TLWALL_REPLACEMENT,
    DUNGEON_NORMAL_TUWALL_REPLACEMENT,
    DUNGEON_NORMAL_TDWALL_REPLACEMENT,
    DUNGEON_NORMAL_HWALL_REPLACEMENT,
    DUNGEON_NORMAL_TLCORN_REPLACEMENT,
    DUNGEON_NORMAL_TRCORN_REPLACEMENT,
    DUNGEON_NORMAL_BLCORN_REPLACEMENT,
    DUNGEON_NORMAL_BRCORN_REPLACEMENT,
    COIN_REPLACEMENT,
    STONE_PEBBLE_REPLACEMENT,
    CLAY_PEBBLE_REPLACEMENT,
    HANDCRAFTED_CANDLE_LIT_REPLACEMENT,
    TWISTED_CANDLE_LIT_REPLACEMENT,
    OLD_FASHIONED_CANDLE_LIT_REPLACEMENT,
    ORIENTAL_BRASS_LAMP_LIT_REPLACEMENT,
    ANTIQUATED_BRASS_LAMP_LIT_REPLACEMENT,
    LAWFUL_ALTAR_REPLACEMENT,
    NEUTRAL_ALTAR_REPLACEMENT,
    CHAOTIC_ALTAR_REPLACEMENT,
    ALTAR_OF_MOLOCH_REPLACEMENT,
    HIGH_ALTAR_REPLACEMENT,
    CHEST_REPLACEMENT,
    GOLDEN_CHEST_REPLACEMENT,
    DUNGEON_NORMAL_IRON_BAR_REPLACEMENT,
    DUNGEON_NORMAL_WATER_REPLACEMENT,
    DUNGEON_NORMAL_ICE_REPLACEMENT,
    DUNGEON_NORMAL_LAVA_REPLACEMENT,
    DUNGEON_NORMAL_ROOM_REPLACEMENT,
    DUNGEON_NORMAL_GRASS_REPLACEMENT,
    DUNGEON_NORMAL_GRASS_SWAMPY_REPLACEMENT,
    DUNGEON_NORMAL_GROUND_REPLACEMENT,
    DUNGEON_NORMAL_AIR_REPLACEMENT,
    DUNGEON_NORMAL_CLOUD_REPLACEMENT,
    DUNGEON_NORMAL_WATER2_REPLACEMENT,
    DUNGEON_NORMAL_STAIRS_UP_REPLACEMENT,
    DUNGEON_NORMAL_STAIRS_DOWN_REPLACEMENT,
    DUNGEON_NORMAL_TRAPDOOR_REPLACEMENT,
    DUNGEON_NORMAL_HOLE_REPLACEMENT,
    DUNGEON_NORMAL_PIT_REPLACEMENT,
    DUNGEON_NORMAL_SPIKED_PIT_REPLACEMENT,
    DUNGEON_NORMAL_LEVER_REPLACEMENT,
    GNOMISH_MINES_STONE_REPLACEMENT,
    GNOMISH_MINES_VWALL_REPLACEMENT,
    GNOMISH_MINES_CRWALL_REPLACEMENT,
    GNOMISH_MINES_TRWALL_REPLACEMENT,
    GNOMISH_MINES_TLWALL_REPLACEMENT,
    GNOMISH_MINES_TUWALL_REPLACEMENT,
    GNOMISH_MINES_TDWALL_REPLACEMENT,
    GNOMISH_MINES_HWALL_REPLACEMENT,
    GNOMISH_MINES_TLCORN_REPLACEMENT,
    GNOMISH_MINES_TRCORN_REPLACEMENT,
    GNOMISH_MINES_BLCORN_REPLACEMENT,
    GNOMISH_MINES_BRCORN_REPLACEMENT,
    GNOMISH_MINES_IRON_BAR_REPLACEMENT,
    GEHENNOM_STONE_REPLACEMENT,
    GEHENNOM_VWALL_REPLACEMENT,
    GEHENNOM_CRWALL_REPLACEMENT,
    GEHENNOM_TRWALL_REPLACEMENT,
    GEHENNOM_TLWALL_REPLACEMENT,
    GEHENNOM_TUWALL_REPLACEMENT,
    GEHENNOM_TDWALL_REPLACEMENT,
    GEHENNOM_HWALL_REPLACEMENT,
    GEHENNOM_TLCORN_REPLACEMENT,
    GEHENNOM_TRCORN_REPLACEMENT,
    GEHENNOM_BLCORN_REPLACEMENT,
    GEHENNOM_BRCORN_REPLACEMENT,
    GEHENNOM_IRON_BAR_REPLACEMENT,
    DUNGEON_UNDEAD_STONE_REPLACEMENT,
    DUNGEON_UNDEAD_VWALL_REPLACEMENT,
    DUNGEON_UNDEAD_CRWALL_REPLACEMENT,
    DUNGEON_UNDEAD_TRWALL_REPLACEMENT,
    DUNGEON_UNDEAD_TLWALL_REPLACEMENT,
    DUNGEON_UNDEAD_TUWALL_REPLACEMENT,
    DUNGEON_UNDEAD_TDWALL_REPLACEMENT,
    DUNGEON_UNDEAD_HWALL_REPLACEMENT,
    DUNGEON_UNDEAD_TLCORN_REPLACEMENT,
    DUNGEON_UNDEAD_TRCORN_REPLACEMENT,
    DUNGEON_UNDEAD_BLCORN_REPLACEMENT,
    DUNGEON_UNDEAD_BRCORN_REPLACEMENT,
    DUNGEON_UNDEAD_IRON_BAR_REPLACEMENT,
    GEHENNOM_CAVERNOUS_STONE_REPLACEMENT,
    GEHENNOM_CAVERNOUS_VWALL_REPLACEMENT,
    GEHENNOM_CAVERNOUS_CRWALL_REPLACEMENT,
    GEHENNOM_CAVERNOUS_TRWALL_REPLACEMENT,
    GEHENNOM_CAVERNOUS_TLWALL_REPLACEMENT,
    GEHENNOM_CAVERNOUS_TUWALL_REPLACEMENT,
    GEHENNOM_CAVERNOUS_TDWALL_REPLACEMENT,
    GEHENNOM_CAVERNOUS_HWALL_REPLACEMENT,
    GEHENNOM_CAVERNOUS_TLCORN_REPLACEMENT,
    GEHENNOM_CAVERNOUS_TRCORN_REPLACEMENT,
    GEHENNOM_CAVERNOUS_BLCORN_REPLACEMENT,
    GEHENNOM_CAVERNOUS_BRCORN_REPLACEMENT,
    GEHENNOM_CAVERNOUS_IRON_BAR_REPLACEMENT,
    BRASS_LANTERN_LIT_REPLACEMENT,
    BOOKSHELF_REPLACEMENT,
    CANDELABRUM_REPLACEMENT,
    LARGE_FIVE_BRANCHED_CANDELABRUM_REPLACEMENT,
    JAR_YELLOW_REPLACEMENT,
    JAR_PURPLE_REPLACEMENT,
    JAR_WHITE_REPLACEMENT,
    JAR_VIOLET_REPLACEMENT,
    JAR_CRIMSON_REPLACEMENT,
    FIGURINE_REPLACEMENT,
    CHAIN_REPLACEMENT,
    BALL_REPLACEMENT,
    CHAIN_UP_REPLACEMENT,
    CHAIN_RIGHT_REPLACEMENT,
    CHAIN_DOWN_REPLACEMENT,
    CHAIN_LEFT_REPLACEMENT,
    CHAIN_MAIN_REPLACEMENT,
    LONG_WORM_HEAD_REPLACEMENT,
    LONG_WORM_TAIL_REPLACEMENT,
    ELDER_LONG_WORM_HEAD_REPLACEMENT,
    ELDER_LONG_WORM_TAIL_REPLACEMENT,
    ROCK_PIERCER_REPLACEMENT,
    IRON_PIERCER_REPLACEMENT,
    GLASS_PIERCER_REPLACEMENT,
    BEAR_TRAP_REPLACEMENT,
    BRAZIER_REPLACEMENT,
    BRAZIER_SUBTYPE_1_REPLACEMENT,
    BRAZIER_SUBTYPE_2_REPLACEMENT,
    COFFIN_REPLACEMENT,
    SARCOPHAGUS_REPLACEMENT,
    MAX_REPLACEMENTS
};

#define NUM_SHORE_TILES (MAX_FLOOR_SUBTYPES + MAX_GRASS_SUBTYPES + MAX_GROUND_SUBTYPES + MAX_CORRIDOR_SUBTYPES + 7)

#define DUNGEON_NORMAL_STONE_REPLACEMENT_TILES 1
#define QUANTITY_REPLACEMENT_TILES 11
#define HANDCRAFTED_CANDLE_LIT_REPLACEMENT_TILES 1
#define TWISTED_CANDLE_LIT_REPLACEMENT_TILES 1
#define OLD_FASHIONED_CANDLE_LIT_REPLACEMENT_TILES 1
#define ORIENTAL_BRASS_LAMP_LIT_REPLACEMENT_TILES 1
#define ANTIQUATED_BRASS_LAMP_LIT_REPLACEMENT_TILES 1
#define LAWFUL_ALTAR_REPLACEMENT_TILES 1
#define NEUTRAL_ALTAR_REPLACEMENT_TILES 1
#define CHAOTIC_ALTAR_REPLACEMENT_TILES 1
#define ALTAR_OF_MOLOCH_REPLACEMENT_TILES 1
#define HIGH_ALTAR_REPLACEMENT_TILES 1
#define CHEST_REPLACEMENT_TILES 2
#define GOLDEN_CHEST_REPLACEMENT_TILES 2
#define DUNGEON_NORMAL_IRON_BAR_REPLACEMENT_TILES 1
#define DUNGEON_NORMAL_WATER_REPLACEMENT_TILES NUM_SHORE_TILES
#define DUNGEON_NORMAL_ICE_REPLACEMENT_TILES NUM_SHORE_TILES
#define DUNGEON_NORMAL_LAVA_REPLACEMENT_TILES NUM_SHORE_TILES
#define DUNGEON_NORMAL_ROOM_REPLACEMENT_TILES NUM_SHORE_TILES
#define DUNGEON_NORMAL_GRASS_REPLACEMENT_TILES NUM_SHORE_TILES
#define DUNGEON_NORMAL_GRASS_SWAMPY_REPLACEMENT_TILES NUM_SHORE_TILES
#define DUNGEON_NORMAL_GROUND_REPLACEMENT_TILES NUM_SHORE_TILES
#define DUNGEON_NORMAL_AIR_REPLACEMENT_TILES NUM_SHORE_TILES
#define DUNGEON_NORMAL_CLOUD_REPLACEMENT_TILES NUM_SHORE_TILES
#define DUNGEON_NORMAL_WATER2_REPLACEMENT_TILES NUM_SHORE_TILES
#define DUNGEON_NORMAL_STAIRS_UP_REPLACEMENT_TILES 1
#define DUNGEON_NORMAL_STAIRS_DOWN_REPLACEMENT_TILES ((MAX_FLOOR_SUBTYPES + MAX_GRASS_SUBTYPES + MAX_GROUND_SUBTYPES + MAX_CORRIDOR_SUBTYPES) * 2)
#define DUNGEON_NORMAL_TRAPDOOR_REPLACEMENT_TILES (MAX_FLOOR_SUBTYPES + MAX_GRASS_SUBTYPES + MAX_GROUND_SUBTYPES + MAX_CORRIDOR_SUBTYPES)
#define DUNGEON_NORMAL_HOLE_REPLACEMENT_TILES (MAX_FLOOR_SUBTYPES + MAX_GRASS_SUBTYPES + MAX_GROUND_SUBTYPES + MAX_CORRIDOR_SUBTYPES)
#define DUNGEON_NORMAL_PIT_REPLACEMENT_TILES (MAX_FLOOR_SUBTYPES + MAX_GRASS_SUBTYPES + MAX_GROUND_SUBTYPES + MAX_CORRIDOR_SUBTYPES)
#define DUNGEON_NORMAL_SPIKED_PIT_REPLACEMENT_TILES (MAX_FLOOR_SUBTYPES + MAX_GRASS_SUBTYPES + MAX_GROUND_SUBTYPES + MAX_CORRIDOR_SUBTYPES)
#define DUNGEON_NORMAL_LEVER_REPLACEMENT_TILES 1
#define GNOMISH_MINES_STONE_REPLACEMENT_TILES 4
#define GNOMISH_MINES_IRON_BAR_REPLACEMENT_TILES 1
#define GEHENNOM_STONE_REPLACEMENT_TILES 4
#define GEHENNOM_IRON_BAR_REPLACEMENT_TILES 1
#define DUNGEON_UNDEAD_STONE_REPLACEMENT_TILES 4
#define DUNGEON_UNDEAD_IRON_BAR_REPLACEMENT_TILES 1
#define GEHENNOM_CAVERNOUS_STONE_REPLACEMENT_TILES 4
#define GEHENNOM_CAVERNOUS_IRON_BAR_REPLACEMENT_TILES 1
#define BRASS_LANTERN_LIT_REPLACEMENT_TILES 1
#define CANDELABRUM_LIT_REPLACEMENT_TILES 1
#define CHAIN_PUNISHED_REPLACEMENT_TILES 1
#define LONG_WORM_HEAD_REPLACEMENT_TILES 1
#define LONG_WORM_TAIL_REPLACEMENT_TILES 1
#define ELDER_LONG_WORM_HEAD_REPLACEMENT_TILES 1
#define ELDER_LONG_WORM_TAIL_REPLACEMENT_TILES 1
#define ROCK_PIERCER_REPLACEMENT_TILES 2
#define IRON_PIERCER_REPLACEMENT_TILES 2
#define GLASS_PIERCER_REPLACEMENT_TILES 2
#define BEAR_TRAP_REPLACEMENT_TILES 1
#define BRAZIER_REPLACEMENT_TILES 1
#define COFFIN_REPLACEMENT_TILES 1

extern NEARDATA struct replacement_definition replacements[];


/* Special effects */
enum special_effect_types
{
    SPECIAL_EFFECT_TELEPORT_OUT = 0,
    SPECIAL_EFFECT_TELEPORT_IN,
    SPECIAL_EFFECT_LEVEL_TELEPORT_OUT,
    SPECIAL_EFFECT_LEVEL_TELEPORT_IN,
    SPECIAL_EFFECT_GENERIC_SPELL,
    SPECIAL_EFFECT_SUMMON_DEMON,
    SPECIAL_EFFECT_SUMMON_CELESTIAL,
    SPECIAL_EFFECT_SUMMON_NATURE,
    SPECIAL_EFFECT_SUMMON_MONSTER,
    SPECIAL_EFFECT_SUMMON_NASTY,
    SPECIAL_EFFECT_SUMMON_UNDEAD,
    SPECIAL_EFFECT_ANIMATE_DEAD,
    SPECIAL_EFFECT_SUMMON_IN_SMOKE,
    SPECIAL_EFFECT_PUFF_OF_SMOKE,
    SPECIAL_EFFECT_DISINTEGRATED,
    SPECIAL_EFFECT_TRAP_SLEEP_GAS,
    SPECIAL_EFFECT_TRAP_RUST,
    SPECIAL_EFFECT_TRAP_FIRE,
    SPECIAL_EFFECT_MAGIC_TRAP_EFFECT,
    SPECIAL_EFFECT_MAGIC_TRAP_LIGHT_FLASH,
    SPECIAL_EFFECT_ANTIMAGIC_TRAP_EFFECT,
    SPECIAL_EFFECT_POLYMORPH_TRAP_EFFECT,
    SPECIAL_EFFECT_FALLING_ROCK_TRAP_TRAP_DOOR,
    SPECIAL_EFFECT_FALLING_ROCK_TRAP_FALLING_ROCK,
    SPECIAL_EFFECT_LAND_MINE_EXPLOSION,
    SPECIAL_EFFECT_BEAR_TRAP_CLOSE,
    SPECIAL_EFFECT_BEAR_TRAP_OPEN,
    SPECIAL_EFFECT_TRAP_NEEDLE,
    SPECIAL_EFFECT_GENERAL_EXCLAMATION,
    SPECIAL_EFFECT_SMALL_FIERY_EXPLOSION,
    SPECIAL_EFFECT_YELLOW_LIGHT_FLASH,
    SPECIAL_EFFECT_BLACK_LIGHT_FLASH,
    MAX_SPECIAL_EFFECTS
};

struct special_effect_definition {
    const char* name;
    int frames_to_sound;
    int frames_from_sound_to_action;
    int frames_from_action_to_end;
    enum layer_types layer;
    short /*enum replacement_types*/ replacement;
    short /*enum animation_types*/ animation;
    short /*enum enlargement_types*/ enlargement;
};

extern NEARDATA struct special_effect_definition special_effects[MAX_SPECIAL_EFFECTS];


struct game_cursor_definition {
    const char* name;
    short /*enum replacement_types*/ replacement;
    short /*enum animation_types*/ animation;
    short /*enum enlargement_types*/ enlargement;
};


extern NEARDATA struct game_cursor_definition game_cursors[MAX_CURSORS];

struct hit_tile_definition {
    const char* name;
    short /*enum replacement_types*/ replacement;
    short /*enum animation_types*/ animation;
    short /*enum enlargement_types*/ enlargement;
};

extern NEARDATA struct hit_tile_definition hit_tile_definitions[MAX_HIT_TILES];


struct general_tile_definition {
    const char* name;
    short /*enum replacement_types*/ replacement;
    short /*enum animation_types*/ animation;
    short /*enum enlargement_types*/ enlargement;
};

extern NEARDATA struct general_tile_definition general_tile_definitions[MAX_GENERAL_TILES];

#define MAX_PLAYED_SPECIAL_EFFECTS 12  // Must be greater than or equal to MAXNASTIES
#define MAX_PLAYED_ZAP_ANIMATIONS 16

#endif /* ANIMATION_H */