/* This source file is generated by 'makedefs'.  Do not edit. */
#ifndef ANIMTOTALS_H
#define ANIMTOTALS_H

#define	TOTAL_NUM_ANIMATION_FRAMES	11490
#define	TOTAL_NUM_ENLARGEMENT_TILES	7504
#define	TOTAL_NUM_REPLACEMENT_TILES	284

#endif /* ANIMTOTALS_H */
