/* This source file is generated by 'makedefs'.  Do not edit. */
#ifndef ANIMTOTALS_H
#define ANIMTOTALS_H

#define	TOTAL_NUM_ANIMATION_FRAMES	11000
#define	TOTAL_NUM_ENLARGEMENT_TILES	5147
#define	TOTAL_NUM_REPLACEMENT_TILES	279

#endif /* ANIMTOTALS_H */
