/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Thu Sep 26 14:17:40 2019"
#define BUILD_TIME (1569496660UL)

#define VERSION_NUMBER 0x04000e00UL
#define VERSION_FEATURES 0x00060000UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x232a0196UL
#define VERSION_SANITY2 0xf89ae65cUL
#define VERSION_SANITY3 0x00026000UL

#define VERSION_STRING "4.0.14"
#define VERSION_ID \
 "Windows GnollHack Version 4.0.14 - last build Thu Sep 26 14:17:40 2019."
#define COPYRIGHT_BANNER_C \
 "         Version 4.0.14 Windows, built Sep 26 14:17:40 2019."

