/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Fri Aug 23 18:54:11 2019"
#define BUILD_TIME (1566575651UL)

#define VERSION_NUMBER 0x04000b00UL
#define VERSION_FEATURES 0x00060000UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x2322c192UL
#define VERSION_SANITY2 0xf8929600UL
#define VERSION_SANITY3 0x00025000UL

#define VERSION_STRING "4.0.11"
#define VERSION_ID \
 "Windows GnollHack Version 4.0.11 - last build Fri Aug 23 18:54:11 2019."
#define COPYRIGHT_BANNER_C \
 "         Version 4.0.11 Windows, built Aug 23 18:54:11 2019."

