/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Fri Jul 26 18:19:24 2019"
#define BUILD_TIME (1564154364UL)

#define VERSION_NUMBER 0x04000500UL
#define VERSION_FEATURES 0x00060000UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x231e1185UL
#define VERSION_SANITY2 0xf88195d0UL
#define VERSION_SANITY3 0x00025000UL

#define VERSION_STRING "4.0.5"
#define VERSION_ID \
 "Windows GnollHack Version 4.0.5 - last build Fri Jul 26 18:19:24 2019."
#define COPYRIGHT_BANNER_C \
 "         Version 4.0.5 Windows, built Jul 26 18:19:24 2019."

