/*
* Copyright 2020 by Janne Gustafsson
*/ 

#ifndef FOUNTAIN_H
#define FOUNTAIN_H

/* Fountain types */
enum fountain_subtypes
{
	FOUNTAIN_NATURAL = 0,
	FOUNTAIN_MAGIC,
	FOUNTAIN_HEALING,
	FOUNTAIN_MANA,
	FOUNTAIN_POWER,
	FOUNTAIN_POISON,
	FOUNTAIN_WATER,
	MAX_FOUNTAIN_SUBTYPES
};

#define LAST_SHUFFLED_FOUNTAIN FOUNTAIN_POISON

#endif /* FOUNTAIN_H */

