/* GnollHack File Change Notice: This file has been changed from the original. Date of last change: 2021-09-14 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#include "config.h"

const int monstrXXX[] = {
0};
/*
DEPRECATION WARNINGS:
'makedefs -m' is deprecated.  Remove all references
  to it from the build process.
'monstr.c' is deprecated.  Remove all references to
  it from the build process.
monstr[] is deprecated.  Replace monstr[x] with
  mons[x].difficulty
monstr_init() is deprecated.  Remove all references to it.
*/

void NDECL(monstr_init);

void
monstr_init()
{
    return;
}

/*monstr.c*/
