/* GnollHack 4.0 rm.c */
/* Copyright (c) Janne Gustafsson, 2020.                            */
/* GnollHack may be freely redistributed.  See license for details. */

#include "hack.h"

NEARDATA struct location_type_definition level_location_types[MAX_TYPE] = {
    {"STONE", LOCATION_SOUNDSET_NONE},
    {"VWALL", LOCATION_SOUNDSET_NONE},
    {"HWALL", LOCATION_SOUNDSET_NONE},
    {"TLCORNER", LOCATION_SOUNDSET_NONE},
    {"TRCORNER", LOCATION_SOUNDSET_NONE},
    {"BLCORNER", LOCATION_SOUNDSET_NONE},
    {"BRCORNER", LOCATION_SOUNDSET_NONE},
    {"CROSSWALL", LOCATION_SOUNDSET_NONE}, 
    {"TUWALL", LOCATION_SOUNDSET_NONE},
    {"TDWALL", LOCATION_SOUNDSET_NONE},
    {"TLWALL", LOCATION_SOUNDSET_NONE},
    {"TRWALL", LOCATION_SOUNDSET_NONE},
    {"DBWALL", LOCATION_SOUNDSET_NONE},
    {"TREE", LOCATION_SOUNDSET_NONE},
    {"SDOOR", LOCATION_SOUNDSET_NONE},
    {"SCORR", LOCATION_SOUNDSET_NONE},
    {"POOL", LOCATION_SOUNDSET_NONE},
    {"MOAT", LOCATION_SOUNDSET_NONE},
    {"WATER", LOCATION_SOUNDSET_NONE},
    {"DRAWBRIDGE_UP", LOCATION_SOUNDSET_NONE},
    {"LAVAPOOL",LOCATION_SOUNDSET_NONE},
    {"IRON_BARS", LOCATION_SOUNDSET_NONE},
    {"DOOR", LOCATION_SOUNDSET_NONE},
    {"CORR", LOCATION_SOUNDSET_NONE},
    {"ROOM", LOCATION_SOUNDSET_NONE }, 
    {"STAIRS", LOCATION_SOUNDSET_NONE},
    {"LADDER", LOCATION_SOUNDSET_NONE},
    {"FOUNTAIN", LOCATION_SOUNDSET_FOUNTAIN},
    {"THRONE", LOCATION_SOUNDSET_NONE},
    {"SINK", LOCATION_SOUNDSET_NONE }, 
    {"GRAVE", LOCATION_SOUNDSET_NONE},
    {"ALTAR", LOCATION_SOUNDSET_ALTAR},
    {"ICE", LOCATION_SOUNDSET_NONE},
    {"DRAWBRIDGE_DOWN", LOCATION_SOUNDSET_NONE},
    {"AIR", LOCATION_SOUNDSET_NONE},
    {"CLOUD", LOCATION_SOUNDSET_NONE},
    {"GRASS", LOCATION_SOUNDSET_NONE},
    {"UNEXPLORED", LOCATION_SOUNDSET_NONE}
};

/* force linkage */
void
init_rm()
{
    return;
}

/* rm.c */